### ISSUE TITLE
TypeError: 2 arguments required, but only 1 present on formatDistance(planningItemDate)

### ISSUE THREAD

**Issue by guedes** [200ok-ch/organice#116]
While playing with Agenda, I clicked on a DEADLINE timestamp and got:

```
TypeError: 2 arguments required, but only 1 present
    at p (index.js:121)
    at index.js:82
    at immutable.js:3155
    at dt.__iterate (immutable.js:2266)
    at i.Ut.r.__iterateUncached (immutable.js:3154)
    at ce (immutable.js:590)
    at i.$.__iterate (immutable.js:310)
    at i.toArray (immutable.js:4547)
    at dt [as constructor] (immutable.js:2114)
    at Xt (immutable.js:3804)
```

I figured out that export `formatDistance` require at least 2 (two) params:

```js
export default function formatDistance(dirtyDate, dirtyBaseDate, dirtyOptions) {
  if (arguments.length < 2) {
    throw new TypeError('2 arguments required, but only ' + arguments.length + ' present');
  }
...
...
```

And it is actually called with only one (index.js line 82):

```js
...
...
      : `${formatDistance(planningItemDate)} ago`}
```

**Comment by munen** [comment]
Good catch, thank you for creating a detailed issue! :pray:

**Comment by munen** [comment]
@guedes Thank you very much for the bug report. This was bug was due to a breaking change in the library date-fns that I was updating a couple months back that I missed in the update process.

I have now written an integration test for that feature and have fixed it.

Thanks, again, much appreciated! 🙏
