### ISSUE TITLE
Drawers are indented

### ISSUE THREAD

**Issue by Linuus** [200ok-ch/organice#121]
If I have this content:

```
* Foo
:LOGBOOK:
CLOCK: [2019-11-21 Thu 19:40]--[2019-11-21 Thu 19:51] =>  0:11
- Something something...
:END:
```

Then, after changing something and syncing (the heading for instance). It will look like this:

```
* Foo
  :LOGBOOK:
  CLOCK: [2019-11-21 Thu 19:40]--[2019-11-21 Thu 19:51] =>  0:11
  - Something something...
  :END:
```

Notice that the logbook drawer has been indented.

**Comment by munen** [comment]
This is intended behavior, since this is the default Emacs Org mode indentation style.

**Comment by munen** [comment]
Would you be interested in rebuilding the feature so that it takes your personal indentation style into account?

**Comment by Linuus** [comment]
Ah, that's true. I use `org-indent-mode` which seems to change this behavior. Tricky to know that it organice :-/

> Would you be interested in rebuilding the feature so that it takes your personal indentation style into account?

Would be fun but I don't have time right now (two small kids makes it hard 😅). But if I get some time I'll definitely have a look at it! But everything still works so it's not too important.

**Comment by munen** [comment]
>  I use `org-indent-mode` which seems to change this behavior

That explains it, then(;

Since organice is written in JavaScript (and doesn't have access to your elisp files), it does not read in elisp configuration.

Here's a section on the employed configuration strategy of organice: https://github.com/200ok-ch/organice/#customization

> Would be fun but I don't have time right now (two small kids makes
> it hard 😅). But if I get some time I'll definitely have a look at
> it!

Sure thing, kids always take precedence - enjoy them whilst they are small^^

Is it OK for you if I assign you this issue? The rationale is that it doesn't make sense to leave issues open for all [500 variables for customization](https://orgmode.org/manual/Customization.html#Customization) if there is no imminent plan to implement them. It'll quickly become a big mess of issues(;

**Comment by Linuus** [comment]
I think we can close it for now :) If I find some time to work on it I'll reopen. If we assign it to me I think it might scare off other people from adding this feature.

**Comment by munen** [comment]
👍

**Comment by whxvd** [comment]
> This is intended behavior, since this is the default Emacs Org mode indentation style.

Since Org 9.5, the default value of `org-adapt-indentation` has changed to `nil`. So now, the Org mode default is to not indent anything (including drawers). In Org 9.4 the default was `t` (indent everything, including text).

I just wanted to bring this to attention. For now, I have not enough time to learn JavaScript work on it.
