### ISSUE TITLE
Clicking a scheduled/deadline date in agenda crashes sample file

### ISSUE THREAD

**Issue by a13ph** [200ok-ch/organice#123]
Repro: 
Current Firefox/Chrome.
1. open sample file
2. click agenda (calendar) icon
3. click on any date under "scheduled"/"deadline"
4. "Uh oh, you ran into a bug!"

**Comment by munen** [comment]
Dear @a13ph

Thank you for your bug report! It's a duplicate to an issue that was opened four days ago: https://github.com/200ok-ch/organice/issues/116

This was bug was due to a breaking change in the library date-fns that I was updating a couple months back that I missed in the update process.

I have now written an integration test for that feature and have fixed it.

Thanks, again, much appreciated! 🙏
