### ISSUE TITLE
Validate capture templates

### ISSUE THREAD

**Issue by tru2dagame** [200ok-ch/organice#126]
## Here is my capture template:

![image](https://user-images.githubusercontent.com/1673006/69906538-c1f70100-13ff-11ea-8b2a-c748431fe78a.png)

## When I try to use this template, I got this error:
![image](https://user-images.githubusercontent.com/1673006/69906543-ce7b5980-13ff-11ea-85fd-5704b162a31e.png)

**Comment by munen** [comment]
Hi @tru2dagame 

Thank you for the report! It's a good catch - there is a validation missing here. At this point, organice assumes that you'll capture your entries into a header - hence, you'll have to specifiy one.

To be more concrete: Atm, you need to add a "Header path" for the capture template and this header needs to be set in your file. For example your file could look like:

```
* Inbox
```

Then your "header path" would just be "Inbox". And all your captures will go there.

There's three things we can improve here:

1. Trivial: Add documentation that this is required
2. Easy: Add a validation to the form
3. Medium: Refactor the feature so that it works without requiring a header for the capture entries

**Comment by tru2dagame** [comment]
@munen Got it. Thanks. Hope we can improve to just add it without any requiring a header.

**Comment by munen** [comment]
@schoettl I'd say https://github.com/200ok-ch/organice/pull/229 closes this issue. Rationale: Validating the capture template on input isn't necessarily better. Imo it's reasonable for a user to first want to set up a capture template and then adapt the Org structure. What do you think?

**Comment by schoettl** [comment]
I'd vote for closing this, too.

Also, validation is not trivial, because capture templates can be defined for all files, while not all file might have the header defined in the capture template...

**Comment by munen** [comment]
👍
