### ISSUE TITLE
Docker Support

### ISSUE THREAD

**Issue by dotcs** [200ok-ch/organice#132]
**Is your feature request related to a problem? Please describe.**
I as a user might have constraints that do not allow me to use the official website. I still want to use the service, but I want to run my own version of it. 

**Describe the solution you'd like**
Having a Docker container would be great, because it would be easy to use since it does not require to have any knowledge of nodejs, yarn, etc. to install and use the software. Also this allows people to use it in modern infrastructure, such as docker-compose, Kubernetes, etc.

**Describe alternatives you've considered**
By not having a dockerized solution people need to have a setup that allows them to build the software. This requires the correct versions of nodejs (and maybe yarn). It could clash with versions that people already have installed for other projects and thus require them to think about how to handle multiple versions of nodejs, which makes things quite complicated.

**Additional context**
I am working on a PR that adds a Dockerfile and support for docker-compose.

**Comment by dotcs** [comment]
@munen I have created a PR that builds a working Docker image. Having `docker` and `docker-compose` installed, you can cd into the base directory of the project and run `docker-compose up` to build the image and start a container. The service is then listening on `http://localhost:5000`.

Since the docker image is working I'd like to discuss how we can automate the process of building images automatically for new versions and push them to DockerHub. This would simplify the process even more since users can then just download the image from DockerHub without the need to even create the image themselves. I guess it should be quite easy to do when we use TravisCI or similar CI services. Have you already thought about using a CI in this project?

And thanks a lot for implementing organice and

**Comment by munen** [comment]
Hi @dotcs 

Thank you for building out Docker support! :pray: 

First, let me say that I'm happy to pull in this feature, of course! But I'm happy to hear you want to do it right, so let's discuss the next steps before I do so.

First a small hiccup: I did run `docker-compose up` on my machine, but it keeps hanging in step 2:

```
Step 2/10 : RUN apk add --no-cache yarn
 ---> Running in 09fd432a17b3
fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/main/x86_64/APKINDEX.tar.gz
```

The file itself is accessible from my machine, though. I restartet three times. The last time, I left it running and about after 20min, it did continue building the container and start it up!  I usually build my Docker containers from Debian, so I'm happy to leave the Alpine debugging to you(; I'm not saying we should be using Debian as a source, here. It's just what I'm using, because I'm familiar with it. I'm aware that using Alpine will create a smaller image. 

> Have you already thought about using a CI in this project?

Yes, we do have CI/CD using CircleCI on this project. The configuration file is here: 
https://github.com/200ok-ch/organice/blob/master/.circleci/config.yml

If you configure the pipeline to also build a Docker image, I'd be happy to add API credentials to Github for https://hub.docker.com/u/twohundredok. 

Furthermore, could you update the documentation in the deployment section, please? https://github.com/200ok-ch/organice#deployment

Thanks again for this solid contribution! :bowing_man:

**Comment by dotcs** [comment]
I'm glad that you like it. Thanks for the kind words. This makes contributing a pleasure! :)

Alpine Linux does indeed create smaller images, which I thought would be a good idea - although I don't have too much experience with Alpine as well because I'm also mostly building on top of Debian images. But let's try it anyways and see if we can fix this issue. I have found [a discussion](https://github.com/gliderlabs/docker-alpine/issues/307#issuecomment-427465925) that suggests to switch to a different mirror because of networking issues with the original mirror. I kindly ask you to pull the latest version my branch, try it again and see if this works better.

I must have missed that you're already using CircleCI. I haven't used it so far, but I'll try to add the necessary changes to build and push the image. After that I'll update the documentation in the deployment section as well. Thanks for the hint.

Please stay tuned.

**Comment by munen** [comment]
> I'm glad that you like it. Thanks for the kind words. This makes contributing a pleasure! :)

Sure thing - and thank you for your kind words, as well! :pray:  

Making this repo a friendly place and open for contributors is a main goal for me. Happy to hear it work^^

As for Alpine vs. Debian - I'm really open. I'm usually using Debian, because I have well over a decade experience with it - and the Docker containers/docker-compose files that I write tend to be for bigger applications that are non-trivial (for me, at least^^). For those, quality of tooling (which is of course primarily biased due to personal knowledge) is more important than size.

Having said that, thank you for investigating and switching the mirror! Unfortunately, I'm still having the same issue. As long as it's just me, I don't mind, as pulling the base image will be cached. As long as caching also works on CI, that's good. If CI has to regularly re-pull (for some reason), we can investigate further. In any case it would be good if the current CI/CD workflow has precedence over (or is at least not by) building/publishing the Docker image, so that the official instance has the newest version quickly while the Docker image will be updated thereafter. If it's possible to run both in parallel on CircleCi, that would guarantee the fastest build for both options.

Out of curiousness I checked the size difference and Alpine is pretty much half the size of the Debian container.
![image](https://user-images.githubusercontent.com/505721/70422776-9366cf00-1a6c-11ea-84da-0ec2cb8d3c6d.png)

> I must have missed that you're already using CircleCI.

No worries^^ organice is quite a simple tool on the one hand, but on the other it's not a super small project anymore, too(;

> Please stay tuned.

I will. Good luck and enjoy :smile:

**Comment by dotcs** [comment]
> Making this repo a friendly place and open for contributors is a main goal for me. Happy to hear it work^^

Absolutely and I like it! :-)

> Having said that, thank you for investigating and switching the mirror! Unfortunately, I'm still having the same issue. As long as it's just me, I don't mind, as pulling the base image will be cached. As long as caching also works on CI, that's good.

So I did several tests on my machine and on CircleCI and I did not experience any network issues so far. It seems that this is something related to your local internet connection. At least I can't reproduce the problem on my machine. :-/

A CircleCI run could look like this: https://circleci.com/gh/dotcs/organice/12
It does automatically create Docker images and and push them to the DockerHub registry. What you need to define in CircleCI are the two environment variables `DOCKER_HUB_USR` and `DOCKER_HUB_PWD`. Credentials can be created [here on DockerHub](https://hub.docker.com/settings/security).
Since there are no versions of this repository I chose the CircleCI build number as the tag for the Docker image. I also limited pushing the image to DockerHub to the master branch which in my opinion makes sense.

The resulting images of my test runs [can be found here](https://hub.docker.com/r/dotcs/organice/tags). This means a simple `docker run -p 5000:5000 dotcs/organice:latest` should be sufficient to pull the image and run it on your local machine. 
I managed to reduce the file size even further in one of my latest commits by removing the `node_modules` folder because it isn't required for the static site. The image is now 130MB (uncompressed!). I think that is quite good!

> As long as caching also works on CI, that's good.
I'm not sure if CircleCI does cache any Docker layers, but I found it is quite fast. So I guess the current approach should be sufficient, but please have a look and see if we can be better.

I've also updated the readme. I hope that it is what you have expected. I needed to separate the docker-compose file into `docker-compose.yaml` and `docker-compose-dev.yaml` because if the `build` section is there docker-compose always builds image which is not want we want for users that are okay with pulling the image from the DockerHub registry.

So please have a look @munen and let me know what you think.

**Comment by munen** [comment]
> So I did several tests on my machine and on CircleCI and I did not
> experience any network issues so far. It seems that this is
> something related to your local internet connection. At least I
> can't reproduce the problem on my machine. :-/

It was likely just a glitch. Sorry to bother you about it! There's probably about a zillion Docker images built on top of Alpine every day - even if there was a problem, somebody probably would have to fix it quickly^^

Thank you very much for your detailed preparation and documentation - both in the repo and in this issue. This enabled me to just smoothly merge and enjoy the new feature 🙏

>> As long as caching also works on CI, that's good.
>
>I'm not sure if CircleCI does cache any Docker layers, but I found it
>is quite fast. So I guess the current approach should be sufficient,
>but please have a look and see if we can be better.

You're right, it's absolutely fast enough. Running the tests takes <1min, deploying via FTP <2min and pushing the image to Docker Hub <3min whilst the latter two are run in parallel.

Perfect implementation!

> I've also updated the readme. I hope that it is what you have
> expected. 

Sweet! I made one change - I moved the Docker documentation above Heroku, because it's clearly the better option(;

> So please have a look @munen and let me know what you think.

Perfect PR, good and fast collaboration on an issue - nothing more to say than thank you and welcome to the team 🚀🙇

This change will certainly enable new users who didn't want to (or couldn't) use organice.200ok.ch - it's a great change!

I added your contribution with attribution to the CHANGELOG.org file: https://github.com/200ok-ch/organice/commit/0dcfdaa990bedf84343e4c4b98c781622fe76769

**Comment by munen** [comment]
@dotcs If you're happy with the state of this feature, feel free to close the issue.

**Comment by dotcs** [comment]
> Thank you very much for your detailed preparation and documentation - both in the repo and in this issue.

I was an honor, I'm glad that everything worked out smoothly.

> Personally, I'm already adhering to a commit message guideline which would allow creating the relevant semantic release.

I think it would make sense to have semantic versioning. If that counts, I'd vote for it. Having semantic versioning in place would give us an easy way to detect the type of changes that have been published (patch vs. minor vs. major). It helps to quickly detect if there are new features that might be interesting or any breaking changes. And it would fit in with how other projects handle their versions.

> I added your contribution with attribution to the CHANGELOG.org file

I appreciate it. Thanks a lot! :)
