### ISSUE TITLE
FR: Deselect headline by clicking into empty space in `<Entry />`

### ISSUE THREAD

**Issue by aspiers** [200ok-ch/organice#152]
Unless I'm missing something, once I've clicked on a headline and it expands to reveal icons / buttons for editing / narrowing etc., there is no way to hide those icons and buttons again.  I can select another headline, but then the icons and buttons just reappear in a new position above the newly selected headline instead.

If I'm right, please consider this a feature request to allow clicking somewhere to collapse the icons / buttons.

**Comment by munen** [comment]
What is your UX proposal to unselect a header?

**Comment by aspiers** [comment]
That's a very good question which I was struggling to answer! If I get a good idea I'll comment here. In the meantime season's greetings to you and thanks so much for this fantastic software!!

**Comment by munen** [comment]
Thank you very much as well. I’d be stoked if there’s good UX improvements being posted^^ That would constitute a great contribution. 

Happy holidays from the phone and train on the way to another family food gathering😉

**Comment by schoettl** [comment]
I had the same question...

I'd expect that the headline gets deselected when I click on free space below all headlines. That of course can only work *if* there is space below (-> small org files).

**Comment by munen** [comment]
It's great we have a first UX option. If you want to build it, I'm not against it. 

However, I'm not strongly in favor of it, because it will only work for small files. Since it'll stop working for bigger files, it'll break with the important UX mantra [Principle of least astonishment](https://en.wikipedia.org/wiki/Principle_of_least_astonishment). It also will neither work for the sample.org file (which is supposed to show off all features) or y personal files(;

I was thinking on this feature request, too. Maybe a 'long press' could be an option. I'm not totally in favor of that one, because we might want to later introduce more features behind a long press. But one of those could be "deselect".

What are your thoughts?

**Comment by schoettl** [comment]
Yeah, but an extra menu item (in the future long-press menu) only for deselecting would be a bit silly, I think ;)

Another option for deselect would be a click on the empty space in the title bar. It might feel analogous to clicking on empty space below all headlines. And clicking on empty space to deselect is a common pattern in file browsers.

**Comment by aspiers** [comment]
While in general I'm more in favour of allowing flexibility via extra UI options (I *detest* the Apple approach of constantly removing flexibility to the point that the UI becomes almost useless), in this particular case it would feel to me like a failure in UX design if we added an option for such a minor issue.  It would be a tacit acknowledgement of a design trade-off which it would be better to avoid outright.

The ideal solution should be non-intrusive, located in a predictable place, and completely intuitive.  I don't think a long press is great, because that goes against all conventions and is therefore unintuitive (plus it removes the possibility of using that for more conventional uses).  Clicking on empty space is certain better, and I did consider that, but in this case there is not any clear area of empty space which we can guarantee to be present.  Certainly a solution should not only work on small org files ;-)

The best solution I can think of is a standard `x` symbol in the top right corner of the icon area to indicate closing of the modal.  This is universally understood and unobtrusive.  Does that sound OK to you guys?

**Comment by schoettl** [comment]
I think a even less obstrusive solution would be this:

Not adding an extra `x` button but instead making select/deselect and expand/collapse *one* action.

- Currently, when you click on a header, the toolbar appears and the subheaders show up.
- Clicking on the header again, the subheaders collapse but the header is still selected.

**Instead of only collapse, it could also deselect.**

A bit related to this, is this problem: When you select/expand a header, you can't just do the opposite by clicking at the same position, because the toolbar appears *above* the headline and the headline jumps down. I think this should be fixed by swapping headline title and toolbar again.

Arguments for this approach:
- Having no header selected is definetly a good thing (less distraction, a clean view on the actual content), you say it @aspiers 
- Selecting and deselecting is intuitive: one click selects, the next click deselects.
- Always showing the subheaders when the header toolbar is visible is fine because when you're about to edit it anyway, the subheaders shouldn't distract too much.

How about this?

**Comment by aspiers** [comment]
[**@schoettl**](https://github.com/schoettl) commented on [December 31, 2019 10:19 AM](https://github.com/200ok-ch/organice/issues/152#issuecomment-569903862 "2019-12-31T10:19:12Z - Replied by Github Reply Comments"):
> I think a even less obstrusive solution would be this:
> 
> Not adding an extra `x` button but instead making select/deselect and expand/collapse _one_ action.
> 
> *   Currently, when you click on a header, the toolbar appears and the subheaders show up.
> *   Clicking on the header again, the subheaders collapse but the header is still selected.
> 
> **Instead of only collapse, it could also deselect.**

I like where you're going with this, because I don't see a compelling use case for being able to use the toolbar with the subheaders collapsed.  However it raises the question: shouldn't organice support a ternary approach to expand/collapse just like Org does (i.e. collapsed -> expanded sub-headers -> expand everything -> collapsed) rather than just the binary approach of toggling between collapsed and expanded sub-headers?

Although I fear I am now placing us at risk of making this conversation overlap with #169 ...

> A bit related to this, is this problem: When you select/expand a header, you can't just do the opposite by clicking at the same position, because the toolbar appears _above_ the headline and the headline jumps down. I think this should be fixed by swapping headline title and toolbar again.

Yes, the jumping of position is really jarring.  This has already been discussed in #153, for which I must apologise for mixing two separate (albeit related) issues within a single GitHub issue.  I'll split them up for clarity.

> Arguments for this approach:
> 
> *   Having no header selected is definetly a good thing (less distraction, a clean view on the actual content), you say it [@aspiers](https://github.com/aspiers)
> *   Selecting and deselecting is intuitive: one click selects, the next click deselects.
> *   Always showing the subheaders when the header toolbar is visible is fine because when you're about to edit it anyway, the subheaders shouldn't distract too much.

I agree with all three points.

**Comment by munen** [comment]
Thank you for your good discussions! Based on that, I had some thoughts, too.

I like this option best, because it is non-obtrusive:

> Another option for deselect would be a click on the empty space in the title bar.

The alternative option to click a header twice (once to select and another time to de-select) it will only sometimes be what the user wants/needs. Sometimes the user only wants to collapse, but wants to continue working with the header, but would be left without the HeaderActionBar. Hence a third click will be needed which again will expand the subheaders - making it potentially impossible to see the header with it's siblings.

I just wrote and merged https://github.com/200ok-ch/organice/pull/228 which has this changelog:

- Make HeaderBar sticky
  - Making undo/redo, file browser and help always available
    (before it was required to scroll all the way to the top)
- Deselect headline by clicking into the title (or empty space) in
  the HeaderBar

 If that works for you, I'd vote to close this issue.

**Comment by munen** [comment]
> However it raises the question: shouldn't organice support a ternary approach to expand/collapse just like Org does (i.e. collapsed -> expanded sub-headers -> expand everything -> collapsed) rather than just the binary approach of toggling between collapsed and expanded sub-headers?

I wouldn’t mind the ability to collapse all headers in one go. Since this would be another global action (not on a header) for which we kind of ran out of space, I’d say this belongs into the redesign issue.

**Comment by schoettl** [comment]
@munen Thanks, good work! Can you assess, how easy it is, to deselect the selected header when clicking on empty space in the main view (below the last header)?

If it is simple, I still would add this.

Because, even for large org files, if all headers are collapsed, there might be empty space below.

**Comment by aspiers** [comment]
[**@munen**](https://github.com/munen) commented on [January 12, 2020 3:54 PM](https://github.com/200ok-ch/organice/issues/152#issuecomment-573428580 "2020-01-12T15:54:02Z - Replied by Github Reply Comments"):
> I just wrote and merged [#228](https://github.com/200ok-ch/organice/pull/228) which has this changelog:
> 
> *   Make HeaderBar sticky
>     *   Making undo/redo, file browser and help always available  
>         (before it was required to scroll all the way to the top)
> *   Deselect headline by clicking into the title (or empty space) in  
>     the HeaderBar
> 
> If that works for you, I'd vote to close this issue.

Nice!  While it's not super-intuitive for newbies, that's probably not too important.  It's good enough for me :-)  So I'm fine if this is closed now.

[**@munen**](https://github.com/munen) commented on [January 12, 2020 4:03 PM](https://github.com/200ok-ch/organice/issues/152#issuecomment-573429532 "2020-01-12T16:03:18Z - Replied by Github Reply Comments"):
> > However it raises the question: shouldn't organice support a ternary approach to expand/collapse just like Org does (i.e. collapsed -> expanded sub-headers -> expand everything -> collapsed) rather than just the binary approach of toggling between collapsed and expanded sub-headers?
> 
> I wouldn’t mind the ability to collapse all headers in one go.

I'd love that too, but it's a different "axis" of visibility.  In emacs Orgmode:

| Scope | Collapsed | Sub-headers expanded | Everything expanded |
| --- | --- | --- | --- |
| **Whole file** | Shift+Tab | Shift+Tab | Shift+Tab |
| **One header** | Tab | Tab | Tab |

In organice:

| Scope | Collapsed | Sub-headers expanded | Everything expanded |
| --- | --- | --- | --- |
| **Whole file** | not implemented | not implemented | not implemented |
| **One header** | Tap header | not implemented | Tap header |

So I suggest splitting up improvements into at least two separate issues:

1. For a single header, allow expansion of sub-headers without bodies.
2. Allow cycling between the three states to be applied globally to the whole file, not just to a single header.

Want me to file a new enhancement / discussion issue and copy and paste this discussion into it?

**Comment by munen** [comment]
@schoettl 

> Because, even for large org files, if all headers are collapsed, there might be empty space below.

There might - for other people(;

Here's a screenshot of my primary Org file:

![Screen Shot 2020-01-12 at 19 31 11](https://user-images.githubusercontent.com/505721/72223699-26b28900-3572-11ea-87df-6103244ad1d1.png)

**Comment by munen** [comment]
> Can you assess, how easy it is, to deselect the selected header when clicking on empty space in the main view (below the last header)?

![image](https://user-images.githubusercontent.com/505721/72223733-73965f80-3572-11ea-8bc3-44a6d85e375e.png)

There's no dedicated container for the empty space atm. The `header-list-container` just grows inside the `entry-container`. I guess someone could try making a click handler in the `Entry` component. That won't me me, though. I didn't have this feature in my scope and only implemented it, because it was quick and I'd like to quickly get the issue list down which seems to be growing faster than the PR list(;

**Comment by munen** [comment]
@aspiers Thanks for the table and feature comparison!

> Want me to file a new enhancement / discussion issue and copy and paste this discussion into it?

Only if you plan to work on this issue soon. To me it sounds like a someday/maybe task and I don't want an unreadable amount of issues in the backlog. I like working quickly through the backlog without too much time spent on PM. Said differently: It's good when the amount of PRs that close issues is roughly the same as newly opened issues.

**Comment by munen** [comment]
>>     If that works for you, I'd vote to close this issue.

> Nice! While it's not super-intuitive for newbies, that's probably not too important. It's good enough for me :-) So I'm fine if this is closed now.

Thank you. 

I agree it's not super intuitive, but I also wasn't the person opening the issue^^ Just the guy implementing one of the suggestions.

**Comment by munen** [comment]
@schoettl @aspiers I went down the rabbithole and made it a little clearer where the clicking in the title can happen - in the actual title(;

See: https://github.com/200ok-ch/organice/pull/230

**Comment by munen** [comment]
I’m not sure if I’m a fan of showing the file name, though. It’s nice when it fits. Not so nice for longer names - even with all the responsive code. 

Do you guys have thoughts? Leave it or kick it?

**Comment by schoettl** [comment]
> I’m not sure if I’m a fan of showing the file name, though. It’s nice when it fits. Not so nice for longer names - even with all the responsive code.
> 
> Do you guys have thoughts? Leave it or kick it?

I think I'm not a fan. IMO it makes the UI a bit less clean. It is redundant to the URL (at least in a desktop browser where the URL is visible). My smartphones photo gallary does not show the filename of photos either (unless I click on the info icon). Most users will recognize their files.

**Comment by aspiers** [comment]
[**@schoettl**](https://github.com/schoettl) commented on [January 12, 2020 9:11 PM](https://github.com/200ok-ch/organice/issues/152#issuecomment-573457660 "2020-01-12T21:11:57Z - Replied by Github Reply Comments"):
> > I’m not sure if I’m a fan of showing the file name, though. It’s nice when it fits. Not so nice for longer names - even with all the responsive code.
> > 
> > Do you guys have thoughts? Leave it or kick it?

I like it!

> I think I'm not a fan. IMO it makes the UI a bit less clean. It is redundant to the URL (at least in a desktop browser where the URL is visible).

Yes but surely the main usage scenario for organice is smaller devices where the URL *isn't* visible?  In which case it's useful to be able to see which file you're in at a glance.

> My smartphones photo gallary does not show the filename of photos either (unless I click on the info icon). Most users will recognize their files.

Sure, it reduces the cognitive load required to figure out which file you're in.  So being able to recognise it without this feature is not a compelling argument not to include it IMHO.

**Comment by munen** [comment]
Thank you for checking it out and getting quickly back to me!

It looks like there's as many opinions as people on this particular feature. These kinds of features either belong to the bin or behind a setting. This time, I opted for the latter: https://github.com/200ok-ch/organice/pull/231

**Comment by aspiers** [comment]
Great work, thanks!
