### ISSUE TITLE
Search/Task List: Save the last 10 used filter strings and provide them as suggestions

### ISSUE THREAD

**Issue by schoettl** [200ok-ch/organice#162]
For an empty filter input in the task list, there should be a suggestion list containing the last used filter strings.

- A filter string should be saved to a list (and stored in the browser i.e. localStorage)
- The oldest filter string can be removed when the list reached the defined limit
- The suggestions should be sorted by 'last use'
- The suggestions should not contain a duplicate filter string (also, use `trim()`)

More information:
We plan to do this together with a refactoring of the `localStorage` use.
https://github.com/200ok-ch/organice/pull/154#discussion_r361744787

**Comment by chasecaleb** [comment]
I came across this issue and the hard-coded example `lastUsedFilterStrings` while thinking about adding configurable saved queries, what do you think about that idea? For instance I would like to save a task list query of `WORKING|PENDING|BLOCKED` to search for my current work in progress tasks, because that's a pain to type out on mobile. Saving the most recent filter strings would sort of accomplish this, but not exactly since the query would disappear if I do too many other searches.

Personally I would get more mileage out of configuring saved queries, but I think both features are useful so it would be good to implement them in a compatible way. Any thoughts on recent queries vs configurable saved queries vs both? And if both, is one or the other more of a priority to you?

**Comment by schoettl** [comment]
Thank you for coming back to this issue.

I just noticed that the `<datalist>` for suggestions doesn't work on Android. In the browser, when I type "W" it suggests "WORKING" (if this TODO keyword is in use anywhere).

I'm totally OK if you rather like to implement a configured list of queries. Note that there is already a `<datalist>` with hard-coded `lastUsedFilterStrings`. But it is re-populated with suggestions during typing. Only, it's not displayed on Android...

**Comment by munen** [comment]
Oh, reviving this issue would be a goodie.

I have a suggestion on the UX. There's a tool that I regularly use which has a nice bookmarking feature for search queries: https://www.dropbox.com/s/8bbiq22m97n3omr/2021-11-04%2011-40-17.mkv?dl=0

**Comment by munen** [comment]
@schoettl Interesting that the `<datalist>` doesn't work for suggestions. It did work before, didn't it? Maybe there's a JS polyfill to make it work on Android, again.

For completeness: The browsers I use (current Firefox, Chromium and Mobile Safari on iOS) continue to show dropdowns for the suggestions in organice.

**Comment by schoettl** [comment]
> @schoettl Interesting that the `<datalist>` doesn't work for suggestions. It did work before, didn't it? Maybe there's a JS polyfill to make it work on Android, again.

Oh, it's actually Android/Firefox where it doesn't work. I don't remember if it worked on Android/Chrome and cannot test right now.

**Comment by chasecaleb** [comment]
I've put zero effort into figuring out why so far, but I can quickly confirm that it:
- Does NOT work on Android Firefox.
- DOES work on Android Chrome.

---

Regarding UX design: I wholeheartedly approve of @munen's idea from the demo video. Saving queries on the fly is a much more intuitive experience than editing them in some obscure settings menu. The existing live search feedback is also, as you pointed out, another point in favor of doing it like you showed.

If no one beats me to it, I'll try to come up with a POC or a mock of what it could look like in organice when I get a chance. Haven't decided yet whether to focus on this feature or #737 first, but I'm open to suggestions if anyone has a strong preference.

**Comment by munen** [comment]
Happy to hear other people like the proposed UX(;

I have no strong preference towards which issue to tackle first. Personally, I'm quite certain to use this feature more often, but #737 is also something that I'll use regularly. Having said that, this is a FOSS project and you as the contributor get to decide what you're interested in working on - I'm happy to support you on both issues^^

**Comment by munen** [comment]
Currently grooming the issues. We discussed options in this issue about UX and came up with bookmarks. Bookmarks are implemented in https://github.com/200ok-ch/organice/pull/758.

So I assume this issue is implemented in spirit and hence I'm closing it. If someone disagrees and still wants the 'last 10 searches' feature implemented/discussed, feel free to re-open anytime.
