### ISSUE TITLE
As a user, when editing a header which is currently without properties, I want to be able to open the property editor

### ISSUE THREAD

**Issue by schoettl** [200ok-ch/organice#170]
As a workshop supervisor, working with properties to assign tasks to employees or to define why a task is blocked, **I want to be able to open the property editor for a headline even if there are no properties yet**.

- When in description edit mode, there should be a further button below the text input:
- Next to "+ Insert timestamp" there could be "Edit properties" which would open the property editor.

**Alternatives:**
This option could also be in the header toolbar next to the tags button, but there are already so many buttons. So we better keep it in the description edit mode.

**Comment by munen** [comment]
Not having the ability to open the property editor only because there are none yet is defintively a UX bug. I'm all in favor of adding that capability!

For tags, organice has the functionality already. There's a 'tags' button in the headerbar at all times - doesn't matter if the headline includes tags atm or not.

I understand that you don't want to convalute the header toolbar. On the other hand, it could be argued that having different UX for tags and properties editors is bad, too (since they are otherwise very similar).

In any case, let's not argue on where the button should be for the moment. If you want to build it, put it where it feels best for you atm. And we'll take a look at the UX separately. You already started a great issue on that anyway^^

**Comment by schoettl** [comment]
> On the other hand, it could be argued that having different UX for tags and properties editors is bad, too (since they are otherwise very similar).

Good point. I just thought that most organice users don't use properties because the option to create them is still missing ^^ therefore not important enough to put it right in the headerbar.

I will try out what looks/feels better. The overfull headerbar is already a thing we addressed in the UX audit yesterday.
