### ISSUE TITLE
Relative dates (in words) in agenda are wrong, especially for future timestamps

### ISSUE THREAD

**Issue by schoettl** [200ok-ch/organice#175]
In the agenda view when clicking on a date, the view toggles to relative dates, e.g. "3 days ago".

There are two bugs:

- For future dates, it also says "x days ago" while x is OK but the direction "ago" is wrong.
- For all timestamps without time, the difference is bad. E.g., at the time of this writing, 2019-12-29 is "about 23 hours ago". Better would be "today". Same problem for here: 2019-12-28 is "2 days ago".

**Comment by schoettl** [comment]
Bug number two is more complicated:

For timestamps with no time, it is hard to compute a relative time.

If we assume 00:00 as time for timestamp without time:

1. if it is 23:00 and the deadline is tomorrow, then "in 1 hour" is good.
2. if it is 23:00 and the deadline was yesterday, then "2 days ago" (23h+24h) is bad.

If we assume 12:00 (noon) as time for timestamps without time:

1. if it is 23:00 and the deadline is tomorrow, then "in 13 hour" is not totally bad.
2. if it is 23:00 and the deadline was yesterday, then "yesterday" (23h+12h) is good.

If we assume 23:59 as time for timestamps without time:

1. if it is 23:00 and the deadline is tomorrow, then "tomorrow" is good.
2. if it is 23:00 and the deadline was yesterday, then "23 h ago" is good.

https://date-fns.org/v2.2.1/docs/formatDistance

Looks, like the last does best, but don't forget, that 23:00 is only an example time. For 01:00 in the morning it's different!

I think it's best to assume 12:00 (noon) for timestamps without time. This is simple and at least better than assuming 00:00.

**Comment by munen** [comment]
@schoettl I have happily merged your PR, because it was definitively an improvemet on the status quo. What I liked most is utilizing the date-fns function correctly by letting it write the human readable time.

For future reference, this is how the Emacs Org agenda would render for a file containing these edge cases:

![image](https://user-images.githubusercontent.com/505721/72728376-81a93900-3b8d-11ea-9b84-8e319b52d896.png)


It's quite different than organice is doing it right now - and it includes a solution for the conflict regarding time(;
