### ISSUE TITLE
Fix Docker build

### ISSUE THREAD

**Issue by munen** [200ok-ch/organice#183]
Adding a new build step broke the Docker build. For the new search feature, we have a parser geneator which is integrated in `package.json` [here](https://github.com/200ok-ch/organice/blob/master/package.json#L33). It's a simple call to `./bin/compile_search_parser.sh`.

However, when building the Docker container said file cannot be found.

I looked into it for a moment, but didn't see why the file is not included in the image. The `bin` folder is added and includes the other file in the directory. 

Since a broken build/push to Docker breaks the build for the whole project, I disabled creating the Docker image and pushing it here for the time being: https://github.com/200ok-ch/organice/commit/012f00fa295913e17c8b7ee7e34b3e4d1752e284

**Comment by munen** [comment]
@dotcs Do you want to look into why the Docker image fails to include said file and hence the build fails?

**Comment by dotcs** [comment]
Hi @munen
I quickly had a look into it and found the root cause. The alpine image does not include bash, so the scripts could not be executed because they have a `#!/bin/bash` shebang line.
There are two ways to fix the issue. Either rely on `/bin/sh` or install bash. I chose the latter because you already mentioned that you're more familiar with good old Debian based images and I think at least bash should be there. ;)

**Comment by munen** [comment]
Hi @dotcs 
cc @schoettl 

Thanks a bunch for jumping quickly to the task! I must have made a mistake when I build the image locally. It looked to me as if the whole shell script was missing in the `bin` folder which seemed weird.

Thank you for properly debugging and fixing the issue^^

I've merged the PR and confirm that Docker images are again being built and pushed! (https://circleci.com/gh/200ok-ch/organice/514).

Please enjoy the new Search / TaskList feature(;

🙏 🙇

**Comment by dotcs** [comment]
Thank you @munen for confirming that the build works again. That makes me happy! :)
