### ISSUE TITLE
Document rationale/strategy between feature and bug for contributors

### ISSUE THREAD

**Issue by munen** [200ok-ch/organice#185]
- Bugs are when features are broken
- Features are changes to existing features or new ones 

Hence, a discrepancy to Emacs is not by default a bug.

**Comment by aspiers** [comment]
This makes sense to me, otherwise we'd have a million bugs for each tiny area where we lack feature parity with Org :-)  Having said that, as shown in #151 I think there can be areas where *undocumented* imparities violate the Principle of Least Astonishment and therefore qualify as documentation bugs.  (In the #151 case, you kindly already fixed it via d211588.)

In those cases I guess you are using the `documentation` label rather than the `bug` label?  Which also makes perfect sense to me.

Thanks for working to clarify this!

**Comment by munen** [comment]
> This makes sense to me, otherwise we'd have a million bugs for each tiny area where we lack feature parity with Org :-) Having said that, as shown in #151 I think there can be areas where undocumented imparities violate the Principle of Least Astonishment and therefore qualify as documentation bugs. (In the #151 case, you kindly already fixed it via d211588.)

I agree!

> In those cases I guess you are using the documentation label rather than the bug label? Which also makes perfect sense to me.

Yes, we're using the labels as their longer descriptions indicate:

![image](https://user-images.githubusercontent.com/505721/71696647-d4c17480-2db5-11ea-93a8-7291a13e0a2f.png)

Imo it's an important distinction. A `bug` issue usually requires a developer, whereas a `documentation` can be worked on by many more people.

> Thanks for working to clarify this!

Thanks for chiming in and helping out! Documentation is hard - and getting feedback on what works and what is hard to understand is necessary hence I'm very grateful when it's given in a straight manner(;
