### ISSUE TITLE
Filter DONE task states from Task List

### ISSUE THREAD

**Issue by munen** [200ok-ch/organice#205]
The top tasks in the Task List in a 'real world' file are only tasks that are long DONE. For me that would be hundreds of DONE todos before seeing an actionable todo.

**Comment by munen** [comment]
@schoettl Do you concur? Or is this behavior what you expect from the Task List?

**Comment by schoettl** [comment]
Good point! The reason they are on top is, that I sorted first by planning item date and then by headline title which includes the TODO keyword. And DONE comes before TODO.

But you're right it doesn't make sense to see tons of DONE headlines, especially not at the top of the list.

I would not exclude all items with DONE states completely – there should still be the option to get results when using a filter string like `FINISHED :assignee:jakob`.

So I can think of a few options:

1. Add another checkbox "search headlines with DONE state" (or "hide headlines with DONE state")
2. Combine the semantics of the checkbox "search all headlines" and the checkbox from 1. into something like a combobox (single-row select tag). There could be three options "search all headlines", "search all tasks", "search only open tasks". The third one would be a good default.
3. Sort headlines with DONE state to the bottom of the list.
4. Add filter syntax like `state:todo` and `state:done` (the latter would filter all items with *any* DONE state). And then, prefill the filter input with that, like it is in GitHub issues (`is:issue is:open`).

**I would prefer option 3. for now, if the a task list with a lot of tasks does not have performance problems.** That would be very easy, too.

I'm not a fan of option 4. because first I think the meaning is not so obvious and second I think it's better to have an empty filter text field with a useful placeholder instead of a prefilled text. The filter text can get too long for a smartphone display anyway. (And implementing this would not be *my* prioritiy.

I'm also not a fan of option 1. and 2. because it makes the UI a bit more crowded, and less slim.

What do you think?

**Comment by munen** [comment]
@schoettl All good points. Before I answer conclusively, I propose we discuss https://github.com/200ok-ch/organice/pull/206 first, because it has implications on which options are possible. My hope is that you'll like the idea of #206 - then I'll happily go along with option 3 for this issue(;

**Comment by munen** [comment]
![7E977840-7325-42FC-845F-D3BF60A5D039](https://user-images.githubusercontent.com/505721/71764058-33d0d780-2ee3-11ea-8d64-d562740fdba7.png)
![Uploading CEF8F56D-1252-4A9D-AAC7-324ED0630B19.png…]()
![Uploading 5357C18B-03F5-425C-AE1E-E948CDC7C9F3.png…]()
