### ISSUE TITLE
JavaScript heap out of memory on a rasberryPI

### ISSUE THREAD

**Issue by daviderestivo** [200ok-ch/organice#221]
**Describe the bug**
I'm not able to create an optimised build on my raspberryPI.

**To Reproduce**

1. Upgraded to node `13.5.0`

```
diff --git a/package.json b/package.json
index eed0de2..c56cf91 100644
--- a/package.json
+++ b/package.json
@@ -3,7 +3,7 @@
   "version": "0.2.0",
   "private": true,
   "engines": {
-    "node": "^12.13.1"
+    "node": "^13.5.0"
   },
   "dependencies": {
     "bowser": "^2.7.0",
diff --git a/yarn.lock b/yarn.lock
index ae5bacd..ac18fc3 100644
```
Start a build:

```
pi@raspberry:~/organice $ yarn build
yarn run v1.21.1
$ ./bin/compile_search_parser.sh && react-scripts build
Creating an optimized production build...

<--- Last few GCs --->

[22235:0x4df8388]   167437 ms: Mark-sweep 228.8 (231.4) -> 228.3 (231.6) MB, 1582.9 / 0.2 ms  (average mu = 0.079, current mu = 0.018) allocation failure scavenge might not succeed
[22235:0x4df8388]   169190 ms: Mark-sweep 228.9 (231.6) -> 228.4 (231.6) MB, 1725.9 / 0.2 ms  (average mu = 0.047, current mu = 0.015) allocation failure scavenge might not succeed


<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 0xe8db20]
Security context: 0x5628e421 <JSObject>
    1: SourceNode_walk [0x2f4a0751] [/home/pi/organice/node_modules/source-map/lib/source-node.js:~221] [pc=0x5eee2b5c](this=0x523b8879 <SourceNode map = 0x4bddbc01>,0x4d65f8a1 <JSFunction (sfi = 0x5cc3cec9)>)
    2: SourceNode_walk [0x2f4a0751] [/home/pi/organice/node_modules/source-map/lib/source-node.js:~221] [pc=0x5eee2a98](this=0x54fc901d <SourceNode map = 0x4bdd...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory

Writing Node.js report to file: report.20200110.165455.22235.0.001.json
Node.js report completed
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

to be honest I'm not sure it's a problem related to organice, so if not please ignore my request.

Thanks a lot for the help,
Davide

**Comment by munen** [comment]
Hi @daviderestivo 

Thanks for trying out organice!

I have good and bad news. Bad news first: From the error message, I can see that your device seems to have too little memory. Those raspberryPIs are great devices, but those modern JS stacks aren't too kind on resource consumption(;

The good news is: 

- Building organice works (on my machine and on CI [see the [latest build one hour ago](https://app.circleci.com/jobs/github/200ok-ch/organice/705)]).

There's more good news: You can run the latest version of organice even without building it yourself. There's a Docker image (https://github.com/200ok-ch/organice#docker) ready for use.

If running Docker on the raspi isn't a good option, either (I have no experience there), then you could build organice on another machine and use the raspi just as a static web server. 

All the best and good luck using organice! :four_leaf_clover: 

Are you happy with the answer - do you have enough options to go on? If so, I'll close the issue. Otherwise, let's continue the discussion.

**Comment by daviderestivo** [comment]
Ciao @munen,

thanks for the very prompt reply and for the very detailed answer. I decided at the end to build it on my Mac and upload it on the raspberryPi.

Thanks a lot and enjoy your weekend,
Davide

**Comment by munen** [comment]
Hi @daviderestivo 

You're very welcome. I hope you enjoy organice and wish you a great weekend, too!

All the best,
Alain
