### ISSUE TITLE
Broken link in Readme.org

### ISSUE THREAD

**Issue by joelthe1** [200ok-ch/organice#250]
**Describe the bug**
The link on the text `installation instructions` in the Readme.org file is broken. It is found in this section: https://github.com/200ok-ch/organice/blob/master/README.org#progressive-web-app--offline-support

**To Reproduce**
1. Go to https://github.com/200ok-ch/organice/blob/master/README.org#progressive-web-app--offline-support
2. Click on the hyperlinked text: `installation instructions`
3. See the 404

**Expected behavior**
It should ideally redirect to https://organice.200ok.ch/documentation.html#orgfa38071

**Screenshots**
Considered unnecessary.

**Desktop (please complete the following information):**
 - MacOS
 - Firefox, FTW

**Smartphone (please complete the following information):**
 - Device: Any
 - OS: Any
 - Browser: Any

**Additional context**
None

**Comment by munen** [comment]
Hi @joelthe1 

Thank you for posting an issue!

Unfortunately, this is an issue with how Github renders Org files. The link is in regular Org syntax ` `[[installation][installation instructions]]` which is rendered as an incorrect link in Githubs HTML.

Your proposed solution doesn't work unfortunately, because the documentation you're linking to us partially built from the readme itself (see https://organice.200ok.ch/documentation.html#org68786f5). So, Githubs inability to render Org links properly is creating an inception problem^^

The only solution to render Org links in Github 'correctly' (that I know) is to make links to their rendered HTML naming like `[[#installation ][installation]]`. However, this will break links within Emacs and in the documention.

If you're aware on how to make Github render Org in-doc links correctly, I'd be happy to add this change! Otherwise, this issue unfortunately is a 'wontfix'. The best I could do (and did do) is link on the top of the readme to the canonical documentation.

**Comment by joelthe1** [comment]
That sounds tricky. GitHub needs to show more love for Org. I am satisfied with the solution being that the user goes to the generated documentation page directly. Thanks for the response.

**Comment by munen** [comment]
> That sounds tricky. GitHub needs to show more love for Org.

No arguments from me here^^

> Thanks for the response.

Thank you for contributing to organice :pray:
