### ISSUE TITLE
Search an entire directory of org files

### ISSUE THREAD

**Issue by rodelrod** [200ok-ch/organice#256]
**Is your feature request related to a problem? Please describe.**
I would like to have a knowledge base directory consisting of many small-ish org files. For this to work for me, I would need to be able to run a search query across the whole directory from mobile. Search is all I would need for this, and maybe adding small snippets of information.

**Describe the solution you'd like**
As a user, I can search headings across an entire directory, and match for file name, heading, heading properties, heading tags and text inside the heading. 

**Describe alternatives you've considered**
The alternative is having a single big org file containing the full knowledge base, but my KB is proven to be large enough that this becomes unfeasible performance-wise, and also a sync'ing hazard.

**Comment by schoettl** [comment]
Our plan was to refactor some search-related features (search, refiling, task list) into something like a tabbed modal view. A search in multiple files would be a nice addition, but not trivial, because we currently only access one org file at a time.

If you want to work on this, you're welcome! Otherwise, if no one commits to work on the issue we probably have to close it to keep the backlog clean, as documented here https://github.com/200ok-ch/organice/blob/master/CONTRIBUTING.org#how-we-work-with-issues

**Comment by rodelrod** [comment]
I see. This seems like more than I could take at the moment. Thanks.
