### ISSUE TITLE
bundle organice as a nextcloud app

### ISSUE THREAD

**Issue by contrun** [200ok-ch/organice#259]
It would be nice if we have a counterpart of https://github.com/jhass/nextcloud-keeweb for organice. I think bundling organice as a nextcloud app is useful to bypass CORS restriction. Unfortunately, I am not familiar with how to bundle as a project as a nextcloud app.

**Comment by munen** [comment]
organice already supports [many deployment options](https://organice.200ok.ch/documentation.html#org0d946a0) and has documented how to configure [NextCloud and other services](https://organice.200ok.ch/documentation.html#org49a18c3).

If you want to bundle organice as a NextCloud app, feel free to do so. However, we're not doing it.

As per the [contribution guidelines](https://organice.200ok.ch/documentation.html#org62022ee), I'm closing this issue since there's no contributor for it. Feel free to re-open this issue when you find the time and effort to work on it.
