### ISSUE TITLE
Read only mode like minor mode in emacs?

### ISSUE THREAD

**Issue by kotfic** [200ok-ch/organice#278]
**Is your feature request related to a problem? Please describe.**
Sometimes when working with organice on my phone I accidentally swipe or click and edit my org file. Other times I am just reviewing a file and don't need all the (very nice!) controls that are provided. It would be great if there was a way to reduce interface clutter and prevent accidents in these situations. 

**Describe the solution you'd like**
I'd love a button that enabled or disabled `read-only-mode`  like the emacs minor mode. 

**Describe alternatives you've considered**
I haven't really considered any. Maybe there is something i'm missing that would give me similar functionality?

Thanks!

**Comment by schoettl** [comment]
Thank you for your input!

A "lock" button or something for a read-only mode would indeed be a great feature against accidental modifications!

Are you interested to give it a try and provide a pull request? If no one plan to work on this idea, I'm afraid we have to close this issue again. Because, as stated in our [contribution guidelines](https://github.com/200ok-ch/organice/blob/master/CONTRIBUTING.org#how-we-work-with-issues), we want to keep the number of open issues manageable. The issue can of course be re-opened anytime.

**Comment by munen** [comment]
Adding to all the right comments by @schoettl: If you accidentally modify your org doc with organice, you can always just use the undo feature.

**Comment by kotfic** [comment]
Thanks for the response! @schoettl probably best the close the Issue, i'm not much of a JS dev and realistically its too much of a lift to learn the ecosystem to resolve what's only a minor annoyance. @munen I appreciate the pointer.  This is a great piece of software and its really filling a big gap in my workflow.  Thanks again!

**Comment by munen** [comment]
@kotfic Thanks for the kind words and all the best! :pray:
