### ISSUE TITLE
Inconsistency line ending happened whenever I try to create a new heading with Organice

### ISSUE THREAD

**Issue by amuyena** [200ok-ch/organice#291]
**Describe the bug**
After creating a new heading on my Org mode file with Organice, when I opened the same file on my computer with Emacs, it displays the carriage return character `^M ` on every line, except the line of the new heading. 

**Desktop**
 - OS: Windows OS 
 - Browser: Firefox

**Smartphone (please complete the following information):**
 - Device: Huawei
 - OS: Android
 - Browser: Firefox

**Additional context**
I tried to test around and I realized that the problem happen because my files doesn't have a pre-defined coding system. If I open a new file and set the variable `set-buffer-file-coding-system` as Unix, that file can be edited by Organice and opened on my computer without any problem. I guess it's because Organice automatically writes in Unix coding system, and it creates inconsistency with the coding system by default of my file. 

Set a default coding system for every file is one solution for this problem, but I wonder whether this could be prevented by Organice, for other Emacs newbies like me trying to use Orgmode.

**Comment by schoettl** [comment]
Thanks for the report.

Right, organice currently only supports Unix line endings `\n`, not Windows (`^M` = carriage return = `\r` followed by `\n`).

To support it, the steps are roughly:

1. Detect line ending (or make it an option in settings)
2. Parse files
3. Export file content afterwards

Parsing could probably fixed to support both `\n` and \r\n`.

Exporting can be fixed too but this requires access to a new global state value holding the line ending.

Personally, I wouldn't put much effort in this because I'd rather work at the [org-parser project](https://github.com/200ok-ch/org-parser). I hope, it's easier to fix it there.

But I wonder if the Windows line ending are officially supported by orgmode. Can you provide a link to some orgmode documentation? Sure, emacs can change the line ending via the file coding system. But orgmode does a lot more in the background, and if orgmode not fully supports Windows line endings, I wouldn't do so in the parser either.

**Comment by amuyena** [comment]
Thank you for your answer and for your time. 

Indeed, I think this might too much of an effort for a problem can be prevented by informing the Windows user to set their Orgmode file to be written in Unix (mostly for newbie like me for example - today it's the first day I learn about the coding system in Emacs). For now, I don't see any inconvenience  in doing so, except from having to recover and fix the files that already have inconsistency line ending problem. 

Here's some Orgmode documentation that I found while looking a way to fix the problem, it might be helpful for others that might have the same issues as me: 
https://www.gnu.org/software/emacs/manual/html_node/emacs/Text-Coding.html
http://ergoemacs.org/emacs/emacs_line_ending_char.html
https://stackoverflow.com/questions/1674481/how-to-configure-gnu-emacs-to-write-unix-or-dos-formatted-files-by-default

**Comment by amuyena** [comment]
I realized that I didn't really answer to your question 
> But I wonder if the Windows line ending are officially supported by orgmode. Can you provide a link to some orgmode documentation?

I am not sure how much it's FULLY supported, but I suppose it is, since I currently working on Windows and all my files were written in Windows format. 

I switched all of them to Unix, and I don't currently have any problem with it. But since I am not yet a power user of Emacs, I don't think I can really say if I see any issue later by working only in Unix format on Windows.  

I am sorry that my limit of knowledge in Orgmode can't be more helpful on this topic.

**Comment by schoettl** [comment]
Thanks for the information. Right now, I couldn't find documentation if orgmode supports it.

Under the hood, when it comes to export, parsing, ..., orgmode is complex and works e.g. with regexes. And I'm not sure that every contributor cared about CRLF. So it's probably better to just use Unix line endings :)
