### ISSUE TITLE
checkbox total count incorrect when there is a child header 

### ISSUE THREAD

**Issue by tcwinn** [200ok-ch/organice#303]
**Describe the bug**
header item checkbox [count/total] tally is inaccurate when there is a 
child header exist. 

**To Reproduce**
When there is no child header, the checkbox [count/total] tally is as expected: Costco [4/7]
![IMG_EB92C9D473D0-1](https://user-images.githubusercontent.com/137057/83079564-fb1bd100-a030-11ea-92b0-3babe12530af.jpeg)

When there is a child header, the checkbox [count/total] tally is as NOT as expected: Costco [0/1]

![IMG_53D150744CFD-1](https://user-images.githubusercontent.com/137057/83079768-66fe3980-a031-11ea-9214-ab6bfb42bd2b.jpeg)

**Smartphone (please complete the following information):**
 - Device: iPhone11
 - OS: iOS13.4.1
 - Browser: DuckDuckGo

**Comment by munen** [comment]
@tcwinn Thank you for the report.

I understand why you think it's a bug. However it's the same behavior as in upstream Emacs Org mode itself:

![image](https://user-images.githubusercontent.com/505721/83356884-4e5f8d80-a369-11ea-9e1f-2713186b1da6.png)

Since this is the behavior of upstream Org mode, I do not consider this a bug, but as consistent behavior. Would you agree?

**Comment by tcwinn** [comment]
Thanks for pointing this out. I missed the following sentence in https://orgmode.org/manual/Checkboxes.html:
"In a headline, a cookie can count either checkboxes below the heading or TODO states of children, and it displays whatever was changed last."

Please close this one.

**Comment by munen** [comment]
👍
