### ISSUE TITLE
Opening `file://` links only works in one easy case and breaks organice in others

### ISSUE THREAD

**Issue by munen** [200ok-ch/organice#311]
**Describe the bug**

I have to apologize. I have merged PR #307 too quickly without proper testing. Initially, I thought that your solution to 'just' use the URL for opening a file is quite ingenius. Personally, I always envisioned this feature to be more complex. It turns out, the current setup is a little too easy and works only in one simple scenario: Opening files relative to the current file which is also accessible within the sync-backend. It doesn't work for:

1. Opening files with absolute paths (no matter whether the file is in the sync-backend or not)
2. Opening files which are not available in the sync-backend
3. On iOS, when in the PWA full-screen view, clicking any link will be treated as opening an external link which results in leaving the fullscreen PWA and opening the browser. It might well be that the user isn't logged in to Mobile Safari (just the PWA), and then the user would only see the login screen. Even if not, any open link would result in new tab and leaving the PWA.

Especially 1 and 2 leave the user in a state from which organice does not recover. The only solution is a reload which is hard to do on a PWA.   

**To Reproduce**

- Bug 1/2 (on the Desktop): https://www.dropbox.com/s/yaifnyioazlp548/2020-05-31%2011-08-05.mkv?dl=0
- Bug 3 (on iOS): https://www.dropbox.com/s/i4rf8kouae2xvz9/Video%2031.05.20%2C%2011%2022%2047.mp4?dl=0

**Expected behavior**

- File links that can be reached should be reached
- File links that cannot be reached are OK to show a 'file not found', but they shouldn't break organice
- Clicking a link shouldn't throw the user off the PWA

**Desktop (please complete the following information):**
 - OS: iOS and Debian
 - Browser: Mobile Safari and FIrefox

**Comment by munen** [comment]
@aspiers (cc @schoettl): I deeply apologize, but I have merged #307 too eagerly without proper testing. After merging, I found multiple bugs immediately with using my main Org files (which have file links). I have opened an issue for that: https://github.com/200ok-ch/organice/issues/311

Tbh, the three bugs I found should all have been merge blockers. Of course it's on me, that I didn't test properly. But if we can't fix those soon, I'm inclined to revert the merge. It's very easy to get organice into a broken state with the current implementation. And, on `master`, we usually try to include only features that work. They may be a subset of what the feature could be, but they should behave consistently. This new feature, unfortunately, doesn't.

I'm afraid the implementation would have to be changed to:

- Parse the Org file with `file://` links
- On clicking such a link, create an event
- Then, in a new function that will have to be implemented for all sync back-ends, check if that file can be reached
  - If so, open it (not by redirecting, but through an action/reducer)
  - If not, show a message to the user that this file is not reachable through the sync-backend

Of course, there might be other options to implement this feature. I'm just writing this solution down here, because that's how I envisioned the feature before. Since it's not trivial, I haven't gotten around to building it.

**Comment by aspiers** [comment]
Thanks for the excellent bug report, this is very helpful.

Sorry, I just assumed the other backends would work in the obvious way.  BTW the issue is with `file:` links not `file://` links. `file:` links in `.org` files are converted to relative links (no `file://` or any other protocol at all) in the `<a>` element's `href`.

Perhaps there might be a simpler, quicker fix than implementing a new event + function? e.g. simply disable the feature when the backend isn't WebDAV or the link isn't relative (i.e. begins with `file:/`) or doesn't end in `.org` - what do you think? But I agree that ideally we want this working in all backends.

I'm a bit confused why it leaves the PWA in your case because I don't think it does that for me. I'll have to double-check.

**Comment by munen** [comment]
As discussed in #organice (https://matrix.to/#/!DfVpGxoYxpbfAhuimY:matrix.org/$YB9VR9NexrEuSFZKfl7ouQSGpm3m-FGVlHtB6HH8LG4?via=matrix.org&via=ungleich.ch&via=tapenet.org), this is how we'll do it:

Instead of a complete rewrite (or revert):
- Disable the feature for links that don't end in `.org`
- Disable the feature for links that start with `/`, `~` or `..` (maybe I'm missing one. an outlier could be `./../outside.org`^^)

**Comment by schoettl** [comment]
@munen: That pretty much matches what I wanted to add to the discussion earlier:

I don't quite understand why the issue depends on the sync backend? IMO, Organice should always refuse to open absolute paths because Org mode absolute file links should be reserved for real file system paths.

I.e., from an Emacs Org mode user perspective, `/tmp/file.org` is the file under `/tmp`, not a file at the "root" of the shared folder (Dropbox/WebDAV/...).

So I would add:
**Expected behavior**
- Organice should only try to open relative `file:` links in-app.
- Organice should not treat links special that start start with `file://` or `file:/` (i.e., just keep the `target=_blank`)

Relative links that go up too far are also problematic,
e.g. `../test.org` opened from current location `/file/test.org`.

**Comment by munen** [comment]
@schoettl

> I don't quite understand why the issue depends on the sync backend? IMO, Organice should always refuse to open absolute paths because Org mode absolute file links should be reserved for real file system paths.

Your question is absolutely valid; it doesn't depend on the sync backend^^ I think that was a misunderstanding from aspiers, because I mentioned `file://` links where I meant to say `file:` links.

The list of things to change (https://github.com/200ok-ch/organice/issues/311#issuecomment-636475774) is complete (to my understanding) and doesn't include anything specific for sync backends. They should also include the 'expected behavior' as described by you.
