### ISSUE TITLE
Set a priority of task from the task menu

### ISSUE THREAD

**Issue by adamfaryna** [200ok-ch/organice#394]
**Is your feature request related to a problem? Please describe.**

There is no way to set priority of a task other than type it.

**Describe the solution you'd like**

After clicking on task we could have another icon in the menu, that will toggle selection of priority of the task.

**Describe alternatives you've considered**

none

**Additional context**

none

**Comment by schoettl** [comment]
Hm, the toolbar is currently pretty much out of space. I think most collaborators here agree that we don't want to add a third row of icons.

We currently have a open discussion on how we can change the UX to allow more such actions and at the same time get a slim user interface. See #188 

But if there is space for one more icon in the second row, you could implement this feature and we can re-arrange it later?

**Comment by adamfaryna** [comment]
@schoettl Yes, there is a space for one more icon in the second row.

Maybe I will be able to do it in my spare time, but my book is very tight these days. If anyone else would take up the glove it would be much appreciated.

**Comment by munen** [comment]
@adamfaryna It's very likely that other people have tight days as well - and might have other ideas on what to work on(;

Do you want to commit to doing the work or would you like to pay someone to implement it? Otherwise, I'll be closing this issue as per https://github.com/200ok-ch/organice/blob/master/CONTRIBUTING.org#how-we-work-with-issues. If you choose to work on it at some point later, please re-open the issue.

**Comment by adamfaryna** [comment]
@munen ok
