### ISSUE TITLE
organice becomes unresponsive after using the email button

### ISSUE THREAD

**Issue by whudwl** [200ok-ch/organice#443]
**Describe the bug**
Organice becomes totally unresponsive on iOS after the email button is clicked. 
**Only happens if the webpage is sent to desktop.  **
**To Reproduce**
1. Add the organice page to desktop. Start it from there. 
1. Open an org file. Click on any header. 
2. Click on email button. 
3. Cancel the email. 
4. Go back to organice. Nothing works. Has to kill the app. 

**Smartphone (please complete the following information):**
 - Device: [iPhoneXR]
 - OS: [iOS13.6.1]
 - Browser [safari]

**Comment by schoettl** [comment]
Hi @whudwl , what do you mean with "happens if webpage is sent to desktop."?

**Comment by munen** [comment]
@schoettl I think he means "when organice is bookmarked to the desktop", so it runs on SPA mode.

I just tested it on an iPhone Xs (very close) on iOS 13.3.1 and couldn't reproduce.

**Comment by munen** [comment]
@schoettl I've upgraded to iOS 13.6.1 (same version as the reporter) and couldn't reproduce.

I assume it's working. That's why he closed the issue after opening it.

One thing I did see is that we're only exporting the description of the selected header. Not the contents of the subheader.

I'm not using this feature a lot, so I never noticed. But it might make sense to export all content under a header, no?

**Comment by whudwl** [comment]
> @schoettl I think he means "when organice is bookmarked to the desktop", so it runs on SPA mode.
> 
> I just tested it on an iPhone Xs (very close) on iOS 13.3.1 and couldn't reproduce.

You are right. I couldn't reproduce it consistently, so I closed the issue. I was just testing this again and found that the issue only happens on one of my org files. I'll try to find out what scenario triggers the issue exactly and reopen the issue if I manage to do that.

**Comment by munen** [comment]
@whudwl Perfect, thank you!
