### ISSUE TITLE
As a user I want to see summaries of time logged on tasks

### ISSUE THREAD

**Issue by tarnung** [200ok-ch/organice#494]
[Pull request](https://github.com/200ok-ch/organice/pull/497)

The timetracking in LOGBOOK does not provide an easy overview and therefore gets unmanagable quickly.
org mode has:

>C-c C-x C-d (org-clock-display)
>
>Display time summaries for each subtree in the current buffer. 
>This puts overlays at the end of each headline, showing the total time recorded under that heading, including the time of any subheadings. 
>You can use visibility cycling to study the tree, but the overlays disappear when you change the buffer (see variable org-remove-highlights-with-change) or press C-c C-c.

It would be nice to have something similar in organice.

I built a first draft in [a fork](https://github.com/tarnung/organice/tree/feat/org-clock-display).

Questions to be answered:
- Do you want this feature in organice?
- How would the display be activated? 
I added a toggle button to the header bar which is ...debatable.
- How would the display be shown? 
I just added " LOGGED 3:15 " to the end of the header line since I don't have strong frontend skills or sensibilities.
- How could the display be deactivated? 
I have not yet implemented the "the overlays disappear when you change the buffer" part of the org mode feature description. So currently the display is not updated (and does not disappear) on change. It needs to be untoggeled and retoggeled to update it.

**Comment by schoettl** [comment]
I haven't looked at your fork yet, but...

>     * Do you want this feature in organice?

I'd like that feature.

> 
>     * How would the display be activated?
>       I added a toggle button to the header bar which is ...debatable.

I think, currently we have no better place. We could hide it under a new menu icon in the top bar for less important actions.


>     * How would the display be shown?
>       I just added " LOGGED 3:15 " to the end of the header line since I don't have strong frontend skills or sensibilities.

I think, right-aligned in the header title line (like in emacs org-mode) would be a good place.

>     * How could the display be deactivated?
>       I have not yet implemented the "the overlays disappear when you change the buffer" part of the org mode feature description. So currently the display is not updated (and does not disappear) on change. It needs to be untoggeled and retoggeled to update it.

As long as it doesn't update automatically, it could also be hidden automatically after some seconds.

But it shouldn't be too hard to make it update automatically.

**Comment by tarnung** [comment]
> I think, right-aligned in the header title line (like in emacs org-mode) would be a good place.

I placed it there. The caveat about my frontend skills still applies.

> As long as it doesn't update automatically, it could also be hidden automatically after some seconds.
> 
> But it shouldn't be too hard to make it update automatically.

I made it update on log entry stop and log entry update. Of course this does not cover many other possibilities of change like deleting or moving headers/subtrees or text-editing the logbook on a header.
Switching the clock display off on every dirtying change is less nice but would guarantee that the values shown are always correct.

**Comment by munen** [comment]
Hi @tarnung 

I agree adding this functionality would be a great addition!

With regards to the display, I propose to keep it in line with how Emacs implements it as far as it makes sense. `org-clock-display` fills the line with dots and appends the summed up time ephemerally. In Emacs, it doesn't auto-update, because as soon as a writing operation happens, the time disappears. I would have thought that disappear in organice would actually be harder (not that it would be very hard, but harder) than keeping an updated time - due to the architecture of organice (and using Redux as state management), having it auto update should come for free. Hence, I think we can easily have it persist and auto-update.

If my gut feeling about the auto-update is wrong, then your statement " Switching the clock display off on every dirtying change is less nice but would guarantee that the values shown are always correct." totally aplies and would be in line with how Emacs does it. Therefore, that seems like a proper viable route for me.

As for where to put the action, I'm not so sure about the header bar. The reason is that `org-clock-display` is not local to the current header. It's docstring is "Show subtree times in the entire buffer.". `org-clock-report` would be local to the headline, but this feature will quickly be infinitely more complicated to implement in a compatible manner.

So, it's an operation on the global buffer - that's what the floating action buttons are for. However, we've reached the maximum available width for mobile devices on those. Therefore, the two available options that I see are:

1. Change one floating action button into an expandable floating action (like search, movement and capture templates). From a UX point of view, I don't see a rationally pleasing grouping of actions for this. Maybe with some more time to think.

2. Add it as a setting.

Given the available options, I'm currently leaning for option 2, because I don't see a feasible way for option 1. But if someone has a good idea, I'm all ears. Finding a solution for using option 1 would likely open of future development options, as well. 

In any case, thank you for getting involved in developing organice, @tarnung :pray: The proposed functionality would make a great addition to organice!

**Comment by tarnung** [comment]
> I would have thought that disappear in organice would actually be harder (not that it would be very hard, but harder) than keeping an updated time - due to the architecture of organice (and using Redux as state management), having it auto update should come for free. Hence, I think we can easily have it persist and auto-update.

Well, auto-updating comes for free implementation-wise. It's trivial to rerun the function I wrote to calculate all the summed up times after every dirtying action. That's quite a bit of computation overhead though (which probably won't matter for anything but giant org files). Only updating the affected time summaries would be more complicated though.
Deactivating the clock display is just setting a boolean when a dirtying action happens, so it's even easier.
 
> As for where to put the action, I'm not so sure about the header bar. The reason is that `org-clock-display` is not local to the current header. 

I think this is a misunderstanding. The HeaderBar-component I talk about is the menu bar at the very top where the undo/redo buttons are. This would be an option 3 besides the two you mention below. It works for my draft implementation but it's probably not the right place to put it grouping-wise.

> So, it's an operation on the global buffer - that's what the floating action buttons are for. However, we've reached the maximum available width for mobile devices on those. Therefore, the two available options that I see are:
> 
> 1. Change one floating action button into an expandable floating action (like search, movement and capture templates). From a UX point of view, I don't see a rationally pleasing grouping of actions for this. Maybe with some more time to think.

One way to make room would be to relocate sync to the HeaderBar next to undo/redo and replace it with a new expandable floating action for "Toggle Clock Display" and future features. Syncing is an action categorically different from the other floating actions. Also it's a button that is useless for anyone who has auto-sync activated (apart from acting as a spinner).

> 2. Add it as a setting.

This is feasible too. It implies that the clock display is a thing you have always on or always off though. My hunch is that it's more of a thing that i want to toggle when I need it while I usually work without it. I would prefer to be able to toggle it on the main screen if there is a smart way to do it.

**Comment by munen** [comment]
> I think this is a misunderstanding. The HeaderBar-component I talk about is the menu bar at the very top where the undo/redo buttons are. This would be an option 3 besides the two you mention below. It works for my draft implementation but it's probably not the right place to put it grouping-wise.

Yes, that's definitively a misunderstanding on my part. Thank you for clarifying! And you used totally correct terminology, too. The `Header Bar` component is at the top, whereas a `Header` represents a header. Sorry for that.

> One way to make room would be to relocate sync to the HeaderBar next to undo/redo and replace it with a new expandable floating action for "Toggle Clock Display" and future features.

Putting 'sync' in the Header Bar sounds like an option, but adding more functionality there will incur a cost of too much space and conflict with existing features:

- Deselecting a header
- Showing the current filename

> Syncing is an action categorically different from the other floating actions. 

True, as is 'summaries of time logged on tasks'. Hence it's great that we're having a good discussion on the topic. UX is never easy(;

> Also it's a button that is useless for anyone who has auto-sync activated (apart from acting as a spinner).

Not exactly. The sync can and will get stuck in the background (at least on iOS, but I assume also on Android). More on that here: https://github.com/200ok-ch/organice/pull/416/files

I've build the auto-sync feature and have added to it multiple times to get it right. And I still use the button for the reasons mentioned in above PR.

> This is feasible too. It implies that the clock display is a thing you have always on or always off though. My hunch is that it's more of a thing that i want to toggle when I need it while I usually work without it. I would prefer to be able to toggle it on the main screen if there is a smart way to do it.

I agree. Yet, it's only feasible if we find a spot for the feature. Otherwise, adding it as a setting would be a compromise to get the feature in. And once a better UX option is found, we can switch to that.

**Comment by tarnung** [comment]
Thanks for sharing some of your reasoning. I've only been using organice for a few weeks, so I don't know many of the considerations that went into its ux.
> Otherwise, adding it as a setting would be a compromise to get the feature in. And once a better UX option is found, we can switch to that.
This surely is the least intrusive place to put it. I'll modify my code accorningly. I'll create a pull request once I think it's ready.

**Comment by munen** [comment]
Perfect, looking forward to it and thank you 🙏🏻

**Comment by munen** [comment]
Implemented and merged in #497. This issue can be closed.
