### ISSUE TITLE
Cannot login into Dropbox

### ISSUE THREAD

**Issue by schoettl** [200ok-ch/organice#533]
**Describe the bug**
When started with `yarn start`, I cannot sign in to Dropbox. The following error shows up (Chromium left, Firefox right). (I pressed `Ctrl-F5` to reload.)

**To Reproduce**
1. `git pull` (get current master)
2. `yarn start`
3. sign out (if not already signed out)
4. sign in with Dropbox

**Screenshots**

![screenshot-2020-](https://user-images.githubusercontent.com/1301843/97101883-43ebba80-16a1-11eb-9cf1-23cc82ea518c.png)

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Browser: Chromium, Firefox

**Comment by tarnung** [comment]
That's what I get.

![drop](https://user-images.githubusercontent.com/35081013/97104040-d182d680-16b0-11eb-9630-ad40040cd9e4.PNG)

**Comment by schoettl** [comment]
Might be e68db883e5a43e51b3fe7bfd4b11a25cf2345958 , the recent upgrade from Dropbox SDK 5 to 7.

**Comment by tarnung** [comment]
I get an error 400 invalid client id.
My .env file was missing. REACT_APP_DROPBOX_CLIENT_ID is supposed to be my dropbox username, right? I had no truble to get it to work before.

**Comment by munen** [comment]
Did you `yarn install`?

I recently made an upgrade across two major versions of the Dropbox SDK which I also announced in #organice.

**Comment by munen** [comment]
> My .env file was missing. 

In a new clone, that's expected, as `.env` is not checked in. 

The `.env_sample` file used to contain the credentials of Dropbox and Google Drive for organice.200ok.ch, but that's not a good idea at all. I changed this in https://github.com/200ok-ch/organice/pull/515/files.

> REACT_APP_DROPBOX_CLIENT_ID is supposed to be my dropbox username, right?

No, but the docs have you covered. This is how you set up Dropbox login capability: https://organice.200ok.ch/documentation.html#dropbox 

It's also covered in "Development" here: https://organice.200ok.ch/documentation.html#development

>  I had no trouble to get it to work before.

You likely symlinked `.env_sample` to `.env`. That was certainly easier, but it's not really good practice to share credentials for applications in a repo, is it?(; So, changing that was long overdue.

Apologies that this causes some extra work for you two.

If you have trouble creating your own Dropbox or Google Drive application, I can share the credentials with just the two of you over a secure channel.

**Comment by tarnung** [comment]
> In a new clone, that's expected, as .env is not checked in.

Yes, but i had created it before. But I probably deleted it somewhere along the line without noticing.

> No, but the docs have you covered. This is how you set up Dropbox login capability

I read that as only necessary for running your own instance, not for local development (since it's not in that section of the docs).

The docs say
> Then, fill in the blanks in .env with your Dropbox or Google Drive credentials. 

That did not tell me what info to place there. But I now suspect it's the app-key of the dropbox app I have to create.

Thanks for the info. I'll try to get it to work.

**Comment by munen** [comment]
> Yes, but i had created it before. But I probably deleted it somewhere along the line without noticing.

Cannot tell you about that. It's your machine(;

> I read that as only necessary for running your own instance, not for local development (since it's not in that section of the docs).

It says for your 'own instance', which you're technically doing while developing. But I'm splitting hairs here. If something is not clear, it's always the docs that can be improved. At least a link between 'development' and 'synchronization back-ends' is missing here. I've added a PR for that: https://github.com/200ok-ch/organice/pull/535 

If that's not yet clear to you, I'd appreciate if you propse a rephrasing.

**Comment by tarnung** [comment]
Thanks, It's working again for me.

I noticed that I explicitly had to add localhost to the redirect uris. I changed the docs accordingly (#536).

**Comment by munen** [comment]
> Thanks, It's working again for me.

That's good to hear!

> I noticed that I explicitly had to add localhost to the redirect uris. I changed the docs accordingly (#536).

Thank you for updating the docs accordingly.

I didn't know, because it's been a while since I last created a Dropbox app, so we've already got the first win that you did it yourself(;

**Comment by munen** [comment]
One thing we also could add to the 'development' docs: It's not necessary to create a Dropbox or Google Drive apps just to start development on organice. organice  has support for webDAV and ships with a Docker container with a WebDAV server based on Apache.

So, generally speaking, it's not necessary to have a working Dropbox or Google Drive setup locally. That would only be necessary to work on those specific sync back-ends.

Having said that, of course it's convenient to have working setups for those if you want to test on files that are already in those back-ends. At least that's what I'm doing most of the time (with Dropbox).

But it doesn't have to be a barrier, just to get started.

**Comment by munen** [comment]
I have just updated https://github.com/200ok-ch/organice/pull/535 accordingly. The 'development' section now explains in much more detail what the options are to get started concerning synchronization back-ends - and that a developer might not even need them to get started.

**Comment by schoettl** [comment]
Thanks @munen ! Now with the help of the docs I got it work again.

Maybe I enhance the docs [here](https://organice.200ok.ch/documentation.html#dropbox) if I have time in the next weeks. Or if you want to do it in #535, feel free.

- Looks like "Client ID" is now "App Key". Should this also be changed in the environment variable?
- It would help, to specify the required permissions more precisely. Can some left out?

![test](https://user-images.githubusercontent.com/1301843/97108616-0f8ef300-16cf-11eb-83d6-396f62136a73.png)
![grafik](https://user-images.githubusercontent.com/1301843/97108700-67c5f500-16cf-11eb-8ec9-008b16bd8182.png)

**Comment by munen** [comment]
@schoettl 

> Thanks @munen ! Now with the help of the docs I got it work again.

That's good to hear!

> Maybe I enhance the docs here if I have time in the next weeks. Or if you want to do it in #535, feel free.

We can do both(; tarnung already made a change to the "Dropbox" section you've linked to. I think #535 is a good improvement as well. Anything that helped you understand what to do will certainly be helpful for the next person, so adding it to the docs is very welcome^^

> Looks like "Client ID" is now "App Key". Should this also be changed in the environment variable?

Good point. I can see in my account that it has been renamed, as well.

Do you want to do it?

> It would help, to specify the required permissions more precisely. Can some left out?

We do have a section on that in the docs: https://organice.200ok.ch/documentation.html#faq_dropbox

Having said so, it's in the FAQ and neither in the 'development' nor the 'sync back-ends' sections. So we should either merge them or (what I would prefer) to link to it. I'd prefer to keep it in the FAQ, because the question keeps popping up from users of organice.200ok.ch (not necessarily developers).

Maybe it could also be a shorter description in the 'sync back-ends' section where it basically says that the developer can set it up however they want. 

I cannot speak as to which permissions really are required. Your setup looks correct from a superficial look - I've only ran with 'full permissions' (for reasons outlined in the faq linked above). If your setup with specific bermissions works (which it should from the looks of it), then we can certainly document that as an alternative!

**Comment by schoettl** [comment]
Alright, it's on my list. I close this question issue now.

**Comment by munen** [comment]
Nice!

Apologies again for causing the two of you extra work without a proper announcement. That’s on me, I wasn’t planning that regression well enough.
