### ISSUE TITLE
Change the width of the main container

### ISSUE THREAD

**Issue by CharlesGueunet** [200ok-ch/organice#594]
On Firefox especially, the main container is ridiculously thin, see my screenshot:

![image](https://user-images.githubusercontent.com/5412579/100670578-5f607a00-335f-11eb-82dc-1132135d6a85.png)

Even if the main app is larger on Chrome, it still takes less than the fourth of the full screen which is not optimal

I think it could be nice to have a way to increase the width of the main app, or maybe just a full-width mode that would expend it horizontally as much as possible.

For now, I use this app in a Chrome instance that takes only a small vertical space on my screen and serves as a sidebar of my main Firefox. It works but I would prefer having Firefox only.

**Comment by CharlesGueunet** [comment]
With a really simple patch, I have the following result

![image](https://user-images.githubusercontent.com/5412579/100729766-79cf3d80-33c9-11eb-96ae-06578d79affb.png)

here is the patch:

```patch
diff --git a/src/base.css b/src/base.css
index 77a91ea..1678191 100644
--- a/src/base.css
+++ b/src/base.css
@@ -14,7 +14,7 @@
   .action-drawer-container,
   .drawer-inner-container,
   .loading-indicator {
-    max-width: 35em;
+    /* max-width: 35em; */
     margin-left: auto;
     margin-right: auto;
   }
```

**Comment by munen** [comment]
Hi @CharlesGueunet 

Thank you for checking out organice!

I understand what you're saying, but your change is a little bit oversimplified, because it basically just reverts a semantic change that we did last year:

![image](https://user-images.githubusercontent.com/505721/100730312-30332280-33ca-11eb-9553-0a7e42df5c2e.png)

If you want flexibility in the width, I propose to add this as a setting where the user can choose a width. Looking forward to your PR! Let me know if you need help.

**Comment by munen** [comment]
As for the ridicioulus width in Firefox, could you check out how that happens? Because it's supposed to look like this on Firefox:

Never should the body of the Org file be more narrow then the floating action buttons.

![image](https://user-images.githubusercontent.com/505721/100730607-8dc76f00-33ca-11eb-94bb-594f8e42cc36.png)

**Comment by CharlesGueunet** [comment]
Ny screenshot comes from a Firefox 83.0 on Artix Linux (Arch Linux).
The problem may come from my screen as it has a native resolution of 3840x2160 but I use it with a resolution of 1920x1080.

I will try to add a "Expand Horizontally" option to switch between the two mode. I am not really familiar with these framework though so if you have any quick tips to provide that would be kind.

At first, I thought about moving the `max-width` in a separate class and apply this class depending on the option value, does that seems right ?

**Comment by CharlesGueunet** [comment]
Ny screenshot comes from a Firefox 83.0 on Artix Linux (Arch Linux).
The problem may come from my screen as it has a native resolution of 3840x2160 but I use it with a resolution of 1920x1080.

I will try to add a "Expand Horizontally" option to switch between the two mode. I am not really familiar with these framework though so if you have any quick tips to provide that would be kind.

At first, I thought about moving the `max-width` in a separate class and apply this class depending on the option value, does that seems right ?

**Comment by munen** [comment]
> My screenshot comes from a Firefox 83.0 on Artix Linux (Arch Linux).
> The problem may come from my screen as it has a native resolution of 3840x2160 but I use it with a resolution of 1920x1080.

That could be it. Depending on how you've implemented that, the `@media` queries aren't working properly.

>I will try to add a "Expand Horizontally" option to switch between the two mode. I am not really familiar with these framework though so if you have any quick tips to provide that would be kind.

Adding a new setting to organice is a good way to get to know the code base a little bit.

Some tips to get going:

- organice uses [Redux](https://redux.js.org/) for state management.
- If I wouldn't know organice, I'd start by looking at a different switch (like "Show Org filename as title") and duplicate the necessary code for the new switch.

> At first, I thought about moving the `max-width` in a separate class and apply this class depending on the option value, does that seems right?

That sounds about right. I'd probably not do it as a 'on/off' switch, though. If we make it configurable, we can give the user the option to chose the maximum width.

**Comment by CharlesGueunet** [comment]
Hello @munen 

Thank you for the advises, I was able to add a new option in the menu. Now I would like to change the value in the CSS accordingly. For this, I need to impact the Dom attributes of several elements, including the root. Where would be the best place for this processing ?

**Comment by munen** [comment]
*hihi*

Checking out this question is the meat of the issue. Can’t tell you from the top of my head. 

I’m happy to help with testing on desktop and iOS when you’re done.

**Comment by tarnung** [comment]
@CharlesGueunet 
We overwrite css variables to switch between color schemes. Maybe this could be of use for you.
`document.documentElement.style.setProperty(key, value);`

**Comment by CharlesGueunet** [comment]
Thanks you for the tips !
Just to let you know that I am not really available for these days. I am not forgetting this issue and I will come back to it asap.

**Comment by munen** [comment]
👍

**Comment by MisterY** [comment]
Perhaps using vw/vh units would be better than em/rem to cover for these weird cases?

**Comment by munen** [comment]
Since this issue has been on hold for a good while, I took the liberty to make a quick change. I have increased the size of the whole app from [35em to 60em](https://github.com/200ok-ch/organice/commit/338d0c6ef6b233186610b7dd685118c69d94e330).

**Comment by munen** [comment]
@MisterY Thanks for getting involved :pray:

`vw`/`vh` units would work very differently. For example, if set to `50vw`, and I use organice in a split-screen, then my browser would take 50% of the screen whereas organice only takes 50% of that, so there would always be a big margin.

With the `em` setting, if you have a big screen, you can use it in split-screen without margin. If you have a smaller screen, you can even put it full screen without margin. Using `vw`, there would always be a margin.

That is, unless I'm understanding your proposal wrong.

**Comment by munen** [comment]
organice on FF in Debian Linux on a 4k display looks like this for me right now:

![image](https://user-images.githubusercontent.com/505721/174817195-0119f5ae-3bf0-4c12-90ea-d28abee45c6a.png)

It does behave responsively. So when I split my screen in half, it looks like this:

![image](https://user-images.githubusercontent.com/505721/174817415-c7c28fb0-e729-4278-ae43-2fc1a1dee97c.png)

And from there, it becomes smaller and smaller until it reaches smartphone levels. This seems generally reasonable. Of course, there's a discussion to be had for a more dedicated Desktop UX. But that's bigger than just 'widen the container' IMO.

Since this issue has been stale for a year, I'll close it according to the [contributor guidelines](https://github.com/200ok-ch/organice/blob/master/CONTRIBUTING.org).

If you want to work on this issue, please feel free re-open it any time! :pray:
