### ISSUE TITLE
Internal Links

### ISSUE THREAD

**Issue by MisterY** [200ok-ch/organice#630]
**Is your feature request related to a problem? Please describe.**

The internal links, either in the same file/notebook, or across different notebooks, do not work. I've tried using CUSTOM_ID and ID values and neither work. Custom_Id links start with a hash (#) so they open a new window but do not navigate to the link.

**Describe the solution you'd like**

Working links within a notebook and across notebooks.
Examples in the demo .org document.

**Describe alternatives you've considered**
Going back to Markdown solutions for building knowledge bases.

**Additional context**

Links are one of the key components of building a wiki / knowledge base or just linking articles and pointing to a relevant article, etc.
They are extremely useful. The whole HTML concept was based on it. They are a part of Org Mode and I am wondering if they work inside Organice or not. Perhaps I'm just missing something obvious.
I'm using my existing files, created with Orgzly, and they have CUSTOM_ID or ID tags for navigation.

**Comment by MisterY** [comment]
After a little bit of experimenting, I find that

- [[filename.org]] links work for linking to a notebook. It is also possible to go back via back button.
- [[file:filename.org]] work one way. Not possible to go back via back button.

I have not yet been able to link to specific notes using either ID or CUSTOM_ID properties and [[id:...]] or [[#custom_id]] syntax.

**Comment by schoettl** [comment]
Good ideas! Well, internal links are not yet implemented that way. The org-parser project (intended to replace Organice's current parser) at least parses all kinds of links.

But currently in Organice, such links must a) be detected and b) a specific internal link element must be created.

We are happy if you want to work on this! Otherwise, we'll probably close this issue as per https://github.com/200ok-ch/organice/blob/master/CONTRIBUTING.org#how-we-work-with-issues
