### ISSUE TITLE
option to match system light/dark preference

### ISSUE THREAD

**Issue by edrex** [200ok-ch/organice#689]
it would be neat to plumb a third option for the color sche pref, "Follow system preference"

https://css-tricks.com/a-complete-guide-to-dark-mode-on-the-web/#os-level

**Comment by munen** [comment]
Hi @edrex 

Thank you for bringing up this issue and apologies for not having answered it for quite a while. 

Good news! organice already supports exactly what you've asked for. See:

- https://organice.200ok.ch/documentation.html#themes
- https://github.com/200ok-ch/organice/search?q=prefers-color-scheme

If you have any further questions regarding this, please do re-open the issue!

Kind regards,
Zen Monk Alain M. Lafon

**Comment by edrex** [comment]
Ok, it seems like once the user makes a selection (dark/light) there's not an option in the UI to go back to using the system preference, is that right? Maybe that's what this issue should be requesting (I can't reopen).

**Comment by munen** [comment]
> Ok, it seems like once the user makes a selection (dark/light) there's not an option in the UI to go back to using the system preference, is that right?

You are correct. As the docs say: "If you change your color scheme preference directly within organice, this naturally overrides your operating system preference. The color schemes in organice are implemented in a strategy pattern, so that adding new themes is quite easy."

> Maybe that's what this issue should be requesting (I can't reopen).

That's certainly possible. Next to the existing switches for the various themes, there could be a switch for "OS settings".

Would you be interested in working on that?

**Comment by munen** [comment]
Closed by https://github.com/200ok-ch/organice/pull/749
