### ISSUE TITLE
backlinks

### ISSUE THREAD

**Issue by hnspn** [200ok-ch/organice#692]
add an interface where you can see backlinks to a page
something similar to roam or any zettel system

This is not a feature in the default emacs org mode, but there are plugins that add this abillity
org-roam
org-super-links
I don't know if org nice has to match the features of org or it can be a superset.

We could implement this as a simple search for links to the current note when we open it.
Or we could keep the link data in a data structure attached to the note.
I think just seraching could be fast enough.

**Comment by schoettl** [comment]
Hi @hnspn , can you provide a screenshot or wireframe of how this backlinks would look like? Or can you explain the feature you have in mind in more detail?

I guess the Organice UI can provide more/different things than Org-mode does. E.g. we have the search with a special query language. But we probably don't extend the org file syntax rules...

**Comment by munen** [comment]
Hi @hnspn 

Thank you for bringing up this request.

>  I don't know if org nice has to match the features of org or it can be a superset.

There's a section in the docs for you: https://organice.200ok.ch/documentation.html#can-we-add-feature-x-from-plugin-y

Specifically for Roam, this section of the docs apply. The different implementations of Zettelkasten in Emacs are scattered and don't generate the same markup. However, I do like your ideas of implementation with regards to using search or adding metadata as PROPERTIES.

I'm closing this issue, because it's been more than a month that you haven't answered schoettls questions which is in compliance with the contribution guideline: https://organice.200ok.ch/documentation.html#contributing

If you do want to get back to this issue, please feel free to open it any time. I'd be happy to support you in this endeavour!

Kind regards,
Zen Monk Alain M. Lafon
