### ISSUE TITLE
Is it possible to customize TODO keywords

### ISSUE THREAD

**Issue by xeechou** [200ok-ch/organice#766]
Before creating a new issue, please read the "How we work with issues" section in the documentation: https://organice.200ok.ch/documentation.html#how_we_work_with_issues

**Is your feature request related to a problem? Please describe.**
Is it possible to customize TODO keywords, currently I don't see exposed settings about this.

**Describe the solution you'd like**
Is it possible to add customized TODO keywords. Or there already is?

**Additional context**
Most other org mode app supports this feature, like beorg and ogzly.

**Comment by munen** [comment]
The documentation has your back: https://organice.200ok.ch/documentation.html#in_buffer_settings

There is no ui to expose the in buffer settings, yet. Would you be interested in implementing it?

**Comment by wuqui** [comment]
One comment on this: this only words with `#+TODO:`, not with `#+todo:`. It took me a while to figure this out, since lowercase variants work just fine within Emacs. In case others have the same problem. Plus in case you want to extend and implement that.

Before you ask: unfortunately, I can't implement that myself, no. I don't have the skills. Thanks anyway for this cool tool! 👍

**Comment by munen** [comment]
@wuqui Thank you for the report regarding the need for uppercase in-buffer settings. @schoettl fixed that in https://github.com/200ok-ch/organice/pull/776.
