### ISSUE TITLE
Error parsing empty org files

### ISSUE THREAD

**Issue by threddast** [200ok-ch/organice#770]
**Description**
When going from a subdirectory to the parent directory, I noticed that some files from the subdirectory were shown in the parent directory as well, even though they are not located there. Upon further inspection, I noticed that those files were empty org files, writing just a word in them solves the issue. Moreover, if trying to open an empty file from organice you get the error "couldn't parse file" and it's not possible to write anything in it.

**To Reproduce**
1. Navigate to a subdirectory with an empty org file (MTEC in this example)
    <img src="https://user-images.githubusercontent.com/10909886/147651854-c4717bf1-d2a7-460c-8572-b98227441fbf.png" width="500">
    <img src="https://user-images.githubusercontent.com/10909886/147652096-4cac7f44-d091-4bbe-9285-9f8a847b2bd9.png" width="500">

2. Open a empty org file (Management.org)
    <img src="https://user-images.githubusercontent.com/10909886/147652391-f9598d02-426b-428e-af78-af7b0605be32.png" width="500">
3. Go back to the root directory (Management.org appears in the root directory now)
    <img src="https://user-images.githubusercontent.com/10909886/147652751-a92d703f-750d-40d3-9f45-9cf3f3b6bfe5.png" width="500">
4. Repeat root->subdir->root->subdir...
    <img src="https://user-images.githubusercontent.com/10909886/147653034-ee40a204-ea24-42c8-8a71-91a42b81b1f5.png" width="500">
5. After a refresh it's back to the image in point 1

**Expected behavior**
1. Empty org files are correctly parsed and writable
2. Empty files don't get duplicated in the root folder

**Smartphone:**
 - OS: Android 11
 - Browser: Chrome

I just tried on desktop with Firefox and it's reproducible as well.

**Comment by munen** [comment]
Hi @threddast 

Thank you for opening the issue. Showing an error for empty files is not a bug per see as it is documented in https://organice.200ok.ch/documentation.html#usage

![image](https://user-images.githubusercontent.com/505721/147676407-f7ec0646-1da3-4764-801a-c57942b59420.png)

The reason is that all actions in organice work on a headline. So without a headline, there's no action bar. Having said so, I understand that it would be easier for UX to support empty files. 

Do you have a proposal on how to do that UX-wise and are interested to build the feature?

For reference, previous issues:
- https://github.com/200ok-ch/organice/issues/120
- https://github.com/200ok-ch/organice/issues/262

The duplication of the empty Org file in the directory list is in itself a bug, of course. Are you interested in working on that?

Thanks, again, for opening the issue and the clear explanation :pray:
