### ISSUE TITLE
Cannot fully swipe right in portrait mode on android 

### ISSUE THREAD

**Issue by ParetoOptimalDev** [200ok-ch/organice#783]
**Describe the bug*

When I try to mark an item as done by swiping right, it almost gets to the edge to complete but not quite.

If I change to landscape mode it works fine because organice doesn't take up the full screen horizontally.

I'll try to fill in more details later if needed. 

This seems like it could be related to not accounting for phones that use gestures on the left and right edges of the phone though.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ParetoOptimalDev** [comment]
This seems to be working. I wrongly thought the green had to hit the right edge and was swiping right slowly and carefully to not mess up.

When I tried swiping fast it just worked.

**Comment by chasecaleb** [comment]
I actually think this is an issue that could use consideration, thanks to some phones that make the questionable design choice of curving the left/right edges of the screen. For example, on a Samsung Galaxy S9+ it takes me a solid 10+ tries to swipe to delete. I'm using Chrome in vertical orientation, but I'm pretty sure I tried Firefox and had the same frustration.

I imagine for curved phones like mine this happens because it's nearly impossible to register a touch right against the sides. I don't have time to prioritize working on a fix for this myself, but I can definitely make time to test a fix if someone else decides to work on this.
