### ISSUE TITLE
Can I migrate features to org-web, and vice versa?

### ISSUE THREAD

**Issue by kjmatsuda** [200ok-ch/organice#792]
Hi! Thank you for sharing organice. This tool makes me motivated to develop.

I am a user and contributor of org-web.
I implemented list control feature in org-web.
https://github.com/DanielDe/org-web/pull/106

I have a question. In organice, there are features as below:
- org clock like feature
- can run as a PWA

I love these features, and want to migrate to org-web.
And I also like to migrate list control feature to organice.
Can I do that? Is there any problem, like license or something?

**Comment by munen** [comment]
Hi @kjmatsuda 

Thank you for your kind words :pray: 

First, let me say that your list control feature is very nice, indeed! Great work and thank you for the contributions to the community :bow: 

Having said so, it neither makes sense to move code from organice to org-web nor is it legal. organice originally is a fork of org-web ([here's the background](https://github.com/200ok-ch/organice/#org-web)) and has since been governed by the community. In the years since it has accumulated a huge amount of change ([see changelog](https://github.com/200ok-ch/organice/blob/master/changelog.org)), over four times the amount of commits of org-web and close to four times the amount of contributors. It's a completely separate product by now while org-web grew stale already at the time when I started using and working on it. The changes made by the community in organice are protected by the [four freedoms](https://www.fsf.org/events/js-20121019-santiagodecompostela) as it is GPL software.

You are very welcome to use and/org contribute to organice. You are free to use and/org contribute to org-web. As per the licenses, you can migrate features from org-web to organice but not the other way around.

I hope to have clarified your questions and will therefore close this issue. If you have further questions, please feel free to re-open it at any time.

Kind regards and thank you again for your great work! :pray:
