### ISSUE TITLE
As a user, I’d like to be able to create a new org file within organice

### ISSUE THREAD

**Issue by MarkWeberMaths** [200ok-ch/organice#87]
At the moment I can achieve this on my devices if I’m connected to a network by creating the file in the Dropbox app, and then opening this in organice. But a “create new file button” would be better.

P.S many thanks for creating this app! As an org lover, I’m thrilled this app exists.

**Comment by munen** [comment]
Hi @MarkWeberMaths 

Thank you for the kind words :pray:  - I'm happy you like using organice^^

Your issue is definitively valid! It's something that I didn't work on so far, because I only have a couple Org files - each up to 10k LOC big. The main structure is within the files. Having said that, I do realize that there's many people creating more files than that^^

Would you be interested in working on that feature? It should be fairly simple. The back-end synchronization libraries already support saving of files, so it would primarily entail creating the user interface for that. Personally, I'm thinking of a `+` sign in the header for the feature, but we could also go with the material design floating button option.

![image](https://user-images.githubusercontent.com/505721/67814295-f8a9c680-faa3-11e9-84b2-4725aff33e3d.png)

**Comment by dixius99** [comment]
I think the plus sign @munen shows looks right to me. I create a new file every day for my journal, though I could do what @munen does and just have a few longer files. I wouldn't know where to start re: implementing something like this, but it would be a nice addition.

**Comment by ihdavids** [comment]
I could really use this as well. Loving gitlab integration. Would love github as well.

**Comment by munen** [comment]
@ihdavids Are you interested in working on this?

**Comment by ihdavids** [comment]
I am attempting to try to make some time.

**Comment by munen** [comment]
@ihdavids Nice!

I'll be happy to support with code review and testing.

:pray:
