### ISSUE TITLE
Making the height of the Description area variable

### ISSUE THREAD

**Issue by dmorlitz** [200ok-ch/organice#872]
I would like to make the height of the textarea in the Description editor variable.  The reason for this request is that I have several descriptions (for example, with tables) that are larger than 8 rows and would be easier to edit if the text area was taller.

So far, I have been able to:
1) Edit the Settings screen to have a number field for the desired height of the Description editor
2) Persist the new setting to the configuration JSON (if the user enables that feature)
3) Found the location in the DescriptionEditorModal where 'rows="8"' was hard-coded
4) Set the default value to my new variable (called editorDescriptionHeightValue) to 8 - so users that don't use this new feature will get the existing behavior

This code has already been pushed to my fork on GitHub.  What I am unable to figure out is how to read the Setting variable inside the DescriptionEditorModal.  I know that (based on my updates) I would need to edit lines 20 and 21 of https://github.com/dmorlitz/organice/blob/master/src/components/OrgFile/components/DescriptionEditorModal/index.js

I just can't figure out the right structure to access the setting variable.

If anyone can provide some suggestions, then I could incorporate those changes into the code and submit this as a PR.

Thank you.

**Comment by dmorlitz** [comment]
I will open a PR for what I have so far and you can see what I have been able to do.  I thought that there was already some awareness of mobile devices (I believe I have seen isMobileBrowser in some of the code) - so I could add 2 number settings - 1 for desktop and 1 for mobile devices

**Comment by munen** [comment]
> I will open a PR for what I have so far and you can see what I have been able to do.

Nice!

>  I thought that there was already some awareness of mobile devices (I believe I have seen isMobileBrowser in some of the code) 

There is. organice is optimized for use on a smartphone with use on the Desktop as 'best effort' currently. The use on Desktop could use some optimization. But there is no setting that works different on Desktop/mobile, right now.

> so I could add 2 number settings - 1 for desktop and 1 for mobile devices

I'm not sure that's the best approach, though. Wouldn't that make it easy for the user to add a setting where her task modal just overflows on mobile? Imo the current setting is one that has been vetted for different sizes. The whole task modal with keyboard is a non-trivial thing on mobile. It's easy to mess up so that the keyboard won't automatically open, won't fit, etc.

**Comment by munen** [comment]
Implemented in https://github.com/200ok-ch/organice/pull/873
