### ISSUE TITLE
Org configuration features

### ISSUE THREAD

**Issue by lhindir** [200ok-ch/organice#91]
This is probably rather premature, but I wanted to ask to get an idea of the timeline.

Is support for setting org variables planned? For example, `org-todo-keywords` and logging preferences like `org-log-into-drawer`, `org-log-{redeadline, reschedule, refile}`, and `org-treat-insert-todo-heading-as-state-change`. I like to log all the changes I make, so I can only use organice read-only for now.

There's usually two ways to do this kind of thing, per-file with `#+` lines and globally with some Emacs configuration. Which ways are planned, and how would a global method look? It might not be possible since it's a client-side app; maybe support a configuration file like `.organice.el` or something in the root directory of the sync backend?

Thanks for any info!

**Comment by munen** [comment]
Hi @lhindir

Thank you for your request.

Your questions and the answers are generally valuable, that's why I wrote a new section "Customization" in the README: https://github.com/200ok-ch/organice#customization

> This is probably rather premature, but I wanted to ask to get an idea of the timeline.

Generally speaking, this is a FOSS project. What the community wants and decides to build, they build. There is no timeline for specific features.

> Is support for setting org variables planned?

organice already understands certain in-buffer settings (`#+TODO` and `#+TYP_TODO`).

> For example, `org-todo-keywords` 

That's the elisp variable for the in-buffer setting `#+TYP_TODO` which is supported. Here's the documentation on how to use it as in-buffer setting: https://orgmode.org/manual/Per_002dfile-keywords.html

> There's usually two ways to do this kind of thing, per-file with `#+` lines and globally with some Emacs configuration. Which ways are planned, and how would a global method look?

After I read your issue, I wrote about this in more detail here: https://github.com/200ok-ch/organice#customization

>  It might not be possible since it's a client-side app; maybe support a configuration file like `.organice.el` or something in the root directory of the sync backend?

This is already implemented(; When you change settings (like setting capture templates, set shortcuts or configure synchronization, organice can write a file `.organice-config.json` to the root of your synchronization back-end. This file will be extended for future configuration options, of course. And by 'can write' I mean this is itself configurable - on whether or not you want to write the configuration to a file.

As I understand, your question was more of a general nature than for specific features. Did I answer them to your satisfaction? If so, let's close this issue.

**Comment by munen** [comment]
Of course, if you're interested in implementing any of the other functionality that you mentioned which is not yet supported (org-log-into-drawer, org-log-{redeadline, reschedule, refile}, and org-treat-insert-todo-heading-as-state-change), I'd be happy to give you pointers on where in the codebase you could hook in.

Are you interested in making a PR?

**Comment by lhindir** [comment]
Yeah, these were just general questions. Unfortunately I can't spend any time on this for now; I was just curious where customization was headed. It looks like there's multiple approaches to fit varying needs. I'd imagine logging settings would go in the settings view. Thanks for the documentation! I'll close this and hope someone else or myself finds the time to contribute :D.
