### ISSUE TITLE
As a user, I want to be prevented from invalidating my Org file by entering a description that leads with `*`

### ISSUE THREAD

**Issue by munen** [200ok-ch/organice#918]
I've seen users create new headings and then adding a list under the new header like:

```
* Foo
* Bar
```

This yields the following Org structure:

```
* New header
* Foo
* Bar
```

This is not what the user wanted. So either, we have to increment the sub-headers automatically, or convert them to dashes.

**Comment by saikiransathpadi** [comment]
Being a newbie to the open-source contribution I thought of picking some issues from organic but while signing in through gitlab I am getting the below error 

`Client authentication failed due to unknown client, no client authentication included, or unsupported authentication method.`

PS: This is the first time I am using gitlab too

**Comment by munen** [comment]
Hi @saikiransathpadi 

thanks for giving it a shot! Are you self hosting organice? If so, you have to configure Gitlab (see the docs). The official instance organice.200ok.ch has such configuration. 

For local development, you need to set up Gitlab yourself. Otherwise you can use the preconfigured WebDAV setup. 

Good luck and all the best!

**Comment by saikiransathpadi** [comment]
I am trying to set it up in the local environment. I have configured GitLab and am now able to sign in. thanks a lot

**Comment by saikiransathpadi** [comment]
https://github.com/200ok-ch/organice/pull/920
I have done the changes to change the leading star to dash, please have a look.

**Comment by munen** [comment]
Closed by https://github.com/200ok-ch/organice/pull/920.
