### ISSUE TITLE
Save to disk instead of synching

### ISSUE THREAD

**Issue by DamienCassou** [200ok-ch/organice#93]
Would it be possible to have organice just save to disk instead of synchronizing? I already synchronize my phone with syncthing and I don't want anything else on top.

**Comment by munen** [comment]
Hi @DamienCassou

Thank you for your question. 

Synchronization in organice is built using the strategy pattern which is consumed here[1]. Implementing a new back-end implies implementing 8 functions[3]. For Dropbox, it’s about 120 LOC JavaScript.

I haven't used Syncthing, personally. However, I did quickly check out the documentation and found that it does have a REST API[3], so I suppose it would be possible to integrate Syncthing.

As for "just saving to disk instead of synchronizing": Accessing the local file system from within a browser is technically not possible for safety reasons. The only option would be to build a back-end for organice. Right now, organice doesn't have any back-end to keep it as simple as possible.

If it is OK for you, I would rename ticket to "Implement Syncthing as a back-end" and add the tags `enhancement`, `help-wanted` and `good first issue`.

1. https://github.com/200ok-ch/organice/blob/master/src/actions/sync_backend.js
2. https://github.com/200ok-ch/organice/blob/master/src/sync_backend_clients/dropbox_sync_backend_client.js#L134-L141
3. https://docs.syncthing.net/dev/rest.html?highlight=rest#rest-api

P.S.: This comment has been discussed during EmacsConf in public and was a demo of magit-forge(;

**Comment by DamienCassou** [comment]
> I did quickly check out the documentation and found that it does have a REST API

I don't think the REST API can be used to synchronize files. Syncthing is really about synchronizing folders on a filesystem.

**Comment by munen** [comment]
@DamienCassou If Syncthing has no API that can be consumed by a browser, then it's not really a suitable option to use it as the back-end for a front-end only web-application(;

Giving the browser access to your Org files through any appropriate protocol is a necessity. Since neither Syncthing nor direct file access to your local files is possible, I suggest to close this issue with a `wontfix`. 

In case you're still interested apart from this issue:  For back-ends that support being accessed from a browser, organice is very flexible. It supports Dropbox, Google Drive and WebDAV. With WebDAV support, organice can potentially be used with a multitude of synchronization backends: Client/Server services ownCloud, Nextcloud and Seafile, but also self hosted dedicated WebDAV servers like Apache or Nginx.

**Comment by DamienCassou** [comment]
"Alain M. Lafon" <notifications@github.com> writes:
> Giving the browser access to your Org files through any appropriate
> protocol is a necessity. Since neither Syncthing nor direct file
> access to your local files is possible, I suggest to close this issue
> with a `wontfix`.

agree.

-- 
Damien Cassou

"Success is the ability to go from one failure to another without
losing enthusiasm." --Winston Churchill

**Comment by munen** [comment]
For future reference, I have added an ADR on how to implement a new synchronization back-end: https://organice.200ok.ch/documentation.html#adr-003
