### ISSUE TITLE
Can't set keyboard shortcut for ⌘↑/⌘↓ on macOS

### ISSUE THREAD

**Issue by telotortium** [200ok-ch/organice#95]
I'd like to change the default keybindings for "Select previous/next heading" on my macOS Chrome browser, since ^↑/^↓ are bound by default on macOS for Expose. However, the browser doesn't seem to allow you to set any keybindings with Command (or any of the other modifier keys such as Shift or Option).

**Comment by munen** [comment]
Hi @telotortium 

Thank you for your report. I got my hand on a macbook for you and tried to set shortcuts using Command, Shift and Option. They all worked:

![demo-shortcuts](https://user-images.githubusercontent.com/505721/68542235-c3a64980-03aa-11ea-911a-e548f9934870.gif)

I assume you tried shortcuts that are not possible to set within a browser, because they are already used by macOS or the browser itself (such as Command-Arrow).

Can you clarify which keybinding you tried and which didn't work?

**Comment by munen** [comment]
Since there's no feedback to this issue and the screencast shows that shortcuts are working, I'm closing the issue.

In case you do have more feedback, feel free to re-open this issue.
