### ISSUE TITLE
Collaborative editing of Org files, similar to Google Docs or gobby.

### ISSUE THREAD

**Issue by aindilis** [200ok-ch/organice#963]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.

Our team is doing a software hackathon, and we're looking for a way to collaboratively edit arguments, like an argument mapping tool, similar to the way Google Docs or gobby allows multiple people to edit together. Even if we just synced to a git repo, and everybody edited that way, that would be a start. I did not see anything about "collaborative" or "multi" in the existing issues that were relevant.

**Describe the solution you'd like**

Either syncing via github or Dropbox, or even a live multiuser view as in Google Docs or gobby.

**Describe alternatives you've considered**

We looked at etherpad, and Argdown, but etherpad lacks the structure of Org-mode, and Argdown doesn't have collaborative mode afaict, although I opened an issue.

**Comment by schoettl** [comment]
Organice has no interactive live editing capabilities. It can sync to Dropbox and other backends after every change but it will lead to conflicts if more people change the same file at the same time.

I think such a feature would be pretty complex to integrate. If you want to work you can, otherwise I would close the issue as per our [contribution guidelines](https://github.com/200ok-ch/organice/blob/master/CONTRIBUTING.org#how-we-work-with-issues).

**Comment by aindilis** [comment]
Okay, thanks!
